import { FamilyMember, FamilyEvent, MemoryItem, VoiceNote } from './types'

// Dynamic today — used so birthday notification always fires in demo mode
const _today = new Date()
const _todayMonth = _today.getMonth() + 1
const _todayDay = _today.getDate()

export const sampleFamilyMembers: FamilyMember[] = [
  // Generation 0 — Great Grandparents (Paternal)
  {
    id: 'g0-1',
    name: 'Ramchandra Sharma',
    birthYear: 1920,
    deathYear: 1995,
    birthPlace: 'Varanasi, Uttar Pradesh',
    currentPlace: 'Varanasi, Uttar Pradesh',
    occupation: 'Sanskrit Scholar & Priest',
    gender: 'male',
    relationship: 'great-grandfather',
    bio: 'A revered Vedic scholar who taught Sanskrit at Kashi Vidyapith. Known for his morning prayers by the Ganga ghats and encyclopedic memory of shlokas.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Varanasi',
    tags: ['elder', 'patriarch', 'scholar', 'historian'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['g0-2'],
    generation: 0,
    isAlive: false,
    milestones: [
      { id: 'm1', title: 'Born in Varanasi', year: 1920, type: 'birth' },
      { id: 'm2', title: 'Joined Kashi Vidyapith', year: 1942, type: 'career' },
      { id: 'm3', title: 'Married Savitri Devi', year: 1940, type: 'marriage' },
      { id: 'm4', title: 'Published Gita Commentary', year: 1965, type: 'achievement' },
    ],
    stories: [
      {
        id: 's1',
        title: 'The Morning Ritual',
        content: 'Every morning at 4am, Ramchandra Sharma would walk barefoot to the Manikarnika Ghat, dip in the Ganga, and recite 108 shlokas before sunrise. This practice never broke for 60 years — not even on the day of Partition riots in 1947, when he lit a lamp on the ghat and prayed for peace.',
        author: 'Suresh Sharma',
        createdAt: '2024-01-15',
        aiGenerated: false,
      }
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g0-2',
    name: 'Savitri Sharma',
    birthYear: 1923,
    deathYear: 2001,
    birthPlace: 'Allahabad, Uttar Pradesh',
    occupation: 'Homemaker & Ayurvedic Healer',
    gender: 'female',
    relationship: 'great-grandmother',
    bio: 'Savitri was famous across three mohallas for her herbal remedies and wisdom. She fed anyone who came to her door, even during scarcity.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Allahabad',
    tags: ['elder', 'matriarch', 'historian'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['g0-1'],
    generation: 0,
    isAlive: false,
    milestones: [
      { id: 'm5', title: 'Born in Allahabad', year: 1923, type: 'birth' },
      { id: 'm6', title: 'Married Ramchandra', year: 1940, type: 'marriage' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g0-3',
    name: 'Jagdish Prasad Mishra',
    birthYear: 1918,
    deathYear: 1990,
    birthPlace: 'Lucknow, Uttar Pradesh',
    occupation: 'Government Officer',
    gender: 'male',
    relationship: 'great-grandfather',
    bio: 'Served in the ICS during British India. Participated in the freedom movement secretly.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Lucknow',
    tags: ['elder', 'patriarch', 'veteran'],
    side: 'maternal',
    parentIds: [],
    spouseIds: ['g0-4'],
    generation: 0,
    isAlive: false,
    milestones: [
      { id: 'm7', title: 'Born in Lucknow', year: 1918, type: 'birth' },
      { id: 'm8', title: 'Joined Civil Service', year: 1940, type: 'career' },
      { id: 'm9', title: 'India Independence witnessed', year: 1947, type: 'achievement' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-10',
  },
  {
    id: 'g0-4',
    name: 'Kamla Devi Mishra',
    birthYear: 1922,
    deathYear: 1998,
    birthPlace: 'Kanpur, Uttar Pradesh',
    occupation: 'Homemaker',
    gender: 'female',
    relationship: 'great-grandmother',
    bio: 'Known for her devotion and her Tulsidas recitation every evening. Her bhajans would fill the entire street.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Kanpur',
    tags: ['elder', 'matriarch'],
    side: 'maternal',
    parentIds: [],
    spouseIds: ['g0-3'],
    generation: 0,
    isAlive: false,
    milestones: [
      { id: 'm10', title: 'Born in Kanpur', year: 1922, type: 'birth' },
      { id: 'm11', title: 'Married Jagdish Prasad', year: 1940, type: 'marriage' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-10',
  },
  // Generation 1 — Grandparents (Paternal)
  {
    id: 'g1-1',
    name: 'Suresh Kumar Sharma',
    birthYear: 1945,
    birthPlace: 'Varanasi, Uttar Pradesh',
    currentPlace: 'Nagpur, Maharashtra',
    occupation: 'Retired School Principal',
    gender: 'male',
    relationship: 'grandfather',
    bio: 'First in the family to move out of UP. Established a school in Nagpur which now has 2000 students. Loved cricket and recited poetry in Urdu.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['elder', 'patriarch', 'scholar'],
    side: 'paternal',
    parentIds: ['g0-1', 'g0-2'],
    spouseIds: ['g1-2'],
    generation: 1,
    isAlive: true,
    milestones: [
      { id: 'm12', title: 'Born in Varanasi', year: 1945, type: 'birth' },
      { id: 'm13', title: 'B.Ed from BHU', year: 1968, type: 'education' },
      { id: 'm14', title: 'Moved to Nagpur', year: 1970, type: 'relocation' },
      { id: 'm15', title: 'Founded Saraswati Vidyalaya', year: 1975, type: 'achievement' },
      { id: 'm16', title: 'Married Laxmi Devi', year: 1968, type: 'marriage' },
    ],
    stories: [
      {
        id: 's2',
        title: 'The Move to Nagpur',
        content: 'In 1970, Suresh boarded a train to Nagpur with only his degrees, a dhoti, and his father\'s blessings. He had secured a teaching job by writing 40 application letters by hand. "Education is the only wealth that cannot be stolen," he always said.',
        author: 'Vikram Sharma',
        createdAt: '2024-02-20',
      }
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g1-2',
    name: 'Laxmi Devi Sharma',
    birthYear: 1948,
    birthPlace: 'Nagpur, Maharashtra',
    currentPlace: 'Nagpur, Maharashtra',
    occupation: 'Retired Teacher',
    gender: 'female',
    relationship: 'grandmother',
    bio: 'Taught Hindi to thousands of students. Famous for her Narali Poornima celebrations blending UP and Maharashtra traditions. Her dal baati churma is legendary.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['elder', 'matriarch'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['g1-1'],
    generation: 1,
    isAlive: true,
    milestones: [
      { id: 'm17', title: 'Born in Nagpur', year: 1948, type: 'birth' },
      { id: 'm18', title: 'Completed BA Hindi', year: 1969, type: 'education' },
      { id: 'm19', title: 'Married Suresh Kumar', year: 1968, type: 'marriage' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  // Generation 1 — Grandparents (Maternal)
  {
    id: 'g1-3',
    name: 'Ramdas Mishra',
    birthYear: 1943,
    birthPlace: 'Lucknow, Uttar Pradesh',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Retired Bank Manager',
    gender: 'male',
    relationship: 'grandfather',
    bio: 'Rose from clerk to Branch Manager in 30 years at SBI. Known for giving loans to poor farmers when no one else would.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: ['elder', 'patriarch'],
    side: 'maternal',
    parentIds: ['g0-3', 'g0-4'],
    spouseIds: ['g1-4'],
    generation: 1,
    isAlive: true,
    milestones: [
      { id: 'm20', title: 'Born in Lucknow', year: 1943, type: 'birth' },
      { id: 'm21', title: 'Joined SBI', year: 1965, type: 'career' },
      { id: 'm22', title: 'Promoted to Branch Manager', year: 1985, type: 'achievement' },
      { id: 'm23', title: 'Married Pushpa Devi', year: 1967, type: 'marriage' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-01-05',
  },
  {
    id: 'g1-4',
    name: 'Pushpa Devi Mishra',
    birthYear: 1947,
    birthPlace: 'Kanpur, Uttar Pradesh',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Homemaker & Social Worker',
    gender: 'female',
    relationship: 'grandmother',
    bio: 'Founded a women\'s self-help group in Pune that empowered 300+ women. Loves Bollywood songs from the 60s and can recite Gulzar verses by heart.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Kanpur',
    tags: ['elder', 'matriarch', 'veteran'],
    side: 'maternal',
    parentIds: [],
    spouseIds: ['g1-3'],
    generation: 1,
    isAlive: true,
    milestones: [
      { id: 'm24', title: 'Born in Kanpur', year: 1947, type: 'birth' },
      { id: 'm25', title: 'Married Ramdas Mishra', year: 1967, type: 'marriage' },
      { id: 'm26', title: 'Founded SHG in Pune', year: 1990, type: 'achievement' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-01-05',
  },
  // Generation 2 — Parents
  {
    id: 'g2-1',
    name: 'Vikram Sharma',
    birthYear: 1972,
    birthPlace: 'Nagpur, Maharashtra',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Civil Engineer',
    gender: 'male',
    relationship: 'father',
    bio: 'Senior civil engineer who built bridges and highways across Maharashtra. Took early morning cycle rides every day for 30 years. Loves Marathi theater.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['patriarch'],
    side: 'paternal',
    parentIds: ['g1-1', 'g1-2'],
    spouseIds: ['g2-2'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm27', title: 'Born in Nagpur', year: 1972, type: 'birth' },
      { id: 'm28', title: 'B.E. Civil from VNIT Nagpur', year: 1994, type: 'education' },
      { id: 'm29', title: 'Married Priya Mishra', year: 1998, type: 'marriage' },
      { id: 'm30', title: 'Built Pune-Nashik Expressway Section', year: 2008, type: 'achievement' },
      { id: 'm31', title: 'Moved to Pune', year: 1998, type: 'relocation' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g2-2',
    name: 'Priya Sharma',
    birthYear: 1975,
    birthPlace: 'Pune, Maharashtra',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'School Principal',
    gender: 'female',
    relationship: 'mother',
    bio: 'Principal of a reputed school in Pune. Advocate for girl child education. Runs a free tuition center on weekends. Loves gardening.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: ['matriarch', 'scholar'],
    side: 'maternal',
    parentIds: ['g1-3', 'g1-4'],
    spouseIds: ['g2-1'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm32', title: 'Born in Pune', year: 1975, type: 'birth' },
      { id: 'm33', title: 'M.Ed from Pune University', year: 1997, type: 'education' },
      { id: 'm34', title: 'Married Vikram Sharma', year: 1998, type: 'marriage' },
      { id: 'm35', title: 'Became School Principal', year: 2015, type: 'career' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  // Generation 2 — Uncle/Aunt (Paternal)
  {
    id: 'g2-3',
    name: 'Deepak Sharma',
    birthYear: 1976,
    birthPlace: 'Nagpur, Maharashtra',
    currentPlace: 'Mumbai, Maharashtra',
    occupation: 'Chartered Accountant',
    gender: 'male',
    relationship: 'uncle',
    bio: "Vikram's younger brother. Moved to Mumbai for work. Known as the 'finance brain' of the family. Loves Sachin Tendulkar and cricket statistics.",
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['scholar'],
    side: 'paternal',
    parentIds: ['g1-1', 'g1-2'],
    spouseIds: ['g2-4'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm36', title: 'Born in Nagpur', year: 1976, type: 'birth' },
      { id: 'm37', title: 'Cleared CA Exams', year: 1999, type: 'education' },
      { id: 'm38', title: 'Married Sunita', year: 2002, type: 'marriage' },
      { id: 'm39', title: 'Moved to Mumbai', year: 2000, type: 'relocation' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-15',
  },
  {
    id: 'g2-4',
    name: 'Sunita Sharma',
    birthYear: 1978,
    birthPlace: 'Mumbai, Maharashtra',
    currentPlace: 'Mumbai, Maharashtra',
    occupation: 'Fashion Designer',
    gender: 'female',
    relationship: 'aunt',
    bio: "Creates traditional Indian wear with modern designs. Runs her own label 'Rang Barse'. Blends Banarasi silk with contemporary cuts.",
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Marathi',
    hometown: 'Mumbai',
    tags: ['artist'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['g2-3'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm40', title: 'Born in Mumbai', year: 1978, type: 'birth' },
      { id: 'm41', title: 'NIFT Graduate', year: 2000, type: 'education' },
      { id: 'm42', title: 'Launched Rang Barse', year: 2010, type: 'achievement' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-15',
  },
  // Generation 2 — Uncle (Maternal)
  {
    id: 'g2-5',
    name: 'Ashok Mishra',
    birthYear: 1978,
    birthPlace: 'Pune, Maharashtra',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'Software Architect',
    gender: 'male',
    relationship: 'uncle',
    bio: "Priya's brother. Works at a top tech company in Bengaluru. Early adopter of everything tech.",
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: [],
    side: 'maternal',
    parentIds: ['g1-3', 'g1-4'],
    spouseIds: ['g2-6'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm43', title: 'Born in Pune', year: 1978, type: 'birth' },
      { id: 'm44', title: 'B.Tech from IIT Bombay', year: 2000, type: 'education' },
      { id: 'm45', title: 'Married Kavitha', year: 2005, type: 'marriage' },
      { id: 'm46', title: 'Moved to Bengaluru', year: 2002, type: 'relocation' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-01-10',
  },
  {
    id: 'g2-6',
    name: 'Kavitha Mishra',
    birthYear: 1980,
    birthPlace: 'Chennai, Tamil Nadu',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'Data Scientist',
    gender: 'female',
    relationship: 'aunt',
    bio: 'South meets North! Kavitha brought idli-sambar to Mishra family pujas. Works on AI models at a global tech firm.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Tamil',
    hometown: 'Chennai',
    tags: ['scholar'],
    side: 'maternal',
    parentIds: [],
    spouseIds: ['g2-5'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm47', title: 'Born in Chennai', year: 1980, type: 'birth' },
      { id: 'm48', title: 'M.Sc. Statistics from IISc', year: 2003, type: 'education' },
      { id: 'm49', title: 'Married Ashok Mishra', year: 2005, type: 'marriage' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-01-10',
  },
  // Generation 3 — You & Siblings
  {
    id: 'g3-1',
    name: 'Rahul Sharma',
    birthYear: 2000,
    birthMonth: _todayMonth,
    birthDay: _todayDay,
    birthPlace: 'Pune, Maharashtra',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Software Developer & Family Historian',
    gender: 'male',
    relationship: 'self',
    bio: 'Built this Family Graph to preserve our roots. CS graduate from Pune University. Loves trekking in Sahyadri, playing tabla, and spicy misal pav.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: ['youth', 'scholar', 'historian'],
    side: 'both',
    parentIds: ['g2-1', 'g2-2'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    role: 'admin',
    milestones: [
      { id: 'm50', title: 'Born in Pune', year: 2000, type: 'birth' },
      { id: 'm51', title: 'B.E. Computer Science', year: 2022, type: 'education' },
      { id: 'm52', title: 'Built Family Graph App', year: 2024, type: 'achievement' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g3-2',
    name: 'Sneha Sharma',
    birthYear: 2003,
    birthPlace: 'Pune, Maharashtra',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Medical Student',
    gender: 'female',
    relationship: 'sister',
    bio: 'MBBS 3rd year at BJ Medical College. Wants to be a pediatrician. Paints in her free time.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: ['youth', 'scholar'],
    side: 'both',
    parentIds: ['g2-1', 'g2-2'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm53', title: 'Born in Pune', year: 2003, type: 'birth' },
      { id: 'm54', title: 'NEET qualified', year: 2021, type: 'achievement' },
      { id: 'm55', title: 'Started MBBS at BJ Medical', year: 2021, type: 'education' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  // Generation 3 — Cousins (Paternal)
  {
    id: 'g3-3',
    name: 'Arjun Sharma',
    birthYear: 2004,
    birthPlace: 'Mumbai, Maharashtra',
    currentPlace: 'Mumbai, Maharashtra',
    occupation: 'IIT Student',
    gender: 'male',
    relationship: 'cousin',
    bio: "Deepak's son. JEE Advanced qualified. Loves competitive programming and chess. Wants to build rockets.",
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Mumbai',
    tags: ['youth', 'scholar'],
    side: 'paternal',
    parentIds: ['g2-3', 'g2-4'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm56', title: 'Born in Mumbai', year: 2004, type: 'birth' },
      { id: 'm57', title: 'Won State Chess Championship', year: 2020, type: 'achievement' },
      { id: 'm58', title: 'Qualified JEE Advanced', year: 2022, type: 'achievement' },
    ],
    addedBy: 'Deepak Sharma',
    addedAt: '2024-02-01',
  },
  {
    id: 'g3-4',
    name: 'Riya Sharma',
    birthYear: 2007,
    birthPlace: 'Mumbai, Maharashtra',
    currentPlace: 'Mumbai, Maharashtra',
    occupation: 'School Student',
    gender: 'female',
    relationship: 'cousin',
    bio: 'National-level Bharatanatyam dancer. Dreams of combining classical dance with contemporary music.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Mumbai',
    tags: ['youth', 'artist', 'child'],
    side: 'paternal',
    parentIds: ['g2-3', 'g2-4'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm59', title: 'Born in Mumbai', year: 2007, type: 'birth' },
      { id: 'm60', title: 'Performed at National Dance Festival', year: 2023, type: 'achievement' },
    ],
    addedBy: 'Sunita Sharma',
    addedAt: '2024-02-01',
  },
  // Generation 3 — Cousins (Maternal)
  {
    id: 'g3-5',
    name: 'Karan Mishra',
    birthYear: 2006,
    birthPlace: 'Bengaluru, Karnataka',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'School Student',
    gender: 'male',
    relationship: 'cousin',
    bio: "Ashok's son. Born in Bengaluru, speaks 4 languages. Won robotics competitions across south India.",
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Bengaluru',
    tags: ['youth', 'scholar', 'child'],
    side: 'maternal',
    parentIds: ['g2-5', 'g2-6'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm61', title: 'Born in Bengaluru', year: 2006, type: 'birth' },
      { id: 'm62', title: 'Won South India Robotics Championship', year: 2023, type: 'achievement' },
    ],
    addedBy: 'Ashok Mishra',
    addedAt: '2024-01-20',
  },
  {
    id: 'g3-6',
    name: 'Ananya Mishra',
    birthYear: 2009,
    birthPlace: 'Bengaluru, Karnataka',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'School Student',
    gender: 'female',
    relationship: 'cousin',
    bio: "Ashok and Kavitha's youngest. A budding author who has already published 2 short stories.",
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Tamil',
    hometown: 'Bengaluru',
    tags: ['youth', 'artist', 'child'],
    side: 'maternal',
    parentIds: ['g2-5', 'g2-6'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm63', title: 'Born in Bengaluru', year: 2009, type: 'birth' },
      { id: 'm64', title: "Published first story in Kids' Monthly", year: 2023, type: 'achievement' },
    ],
    addedBy: 'Kavitha Mishra',
    addedAt: '2024-01-20',
  },

  // ── Extended Family ────────────────────────────────────────────────────────
  // Vikram's 2nd cousin (paternal extended blood relative, generation 2)
  {
    id: 'ext-1',
    name: 'Mohan Sharma',
    birthYear: 1968,
    birthPlace: 'Nagpur, Maharashtra',
    currentPlace: 'Nagpur, Maharashtra',
    occupation: 'Civil Contractor',
    gender: 'male',
    relationship: 'second-cousin',
    bio: "Vikram's 2nd cousin on the paternal side. Active in the Nagpur Sharma community. Attends every family reunion.",
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['elder'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['ext-2'],
    generation: 2,
    isAlive: true,
    networkGroup: 'extended',
    milestones: [
      { id: 'me1', title: 'Born in Nagpur', year: 1968, type: 'birth' },
      { id: 'me2', title: 'Married Sudha', year: 1994, type: 'marriage' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-06-01',
  },
  {
    id: 'ext-2',
    name: 'Sudha Sharma',
    birthYear: 1970,
    birthPlace: 'Amravati, Maharashtra',
    currentPlace: 'Nagpur, Maharashtra',
    occupation: 'Teacher',
    gender: 'female',
    relationship: 'second-cousin',
    bio: "Mohan's wife. Primary school teacher, known for her warmth.",
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['scholar'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['ext-1'],
    generation: 2,
    isAlive: true,
    networkGroup: 'extended',
    milestones: [
      { id: 'me3', title: 'Born in Amravati', year: 1970, type: 'birth' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-06-01',
  },
  // Maternal great-uncle (Ramdas's brother, generation 1)
  {
    id: 'ext-3',
    name: 'Shivdas Mishra',
    birthYear: 1945,
    deathYear: 2018,
    birthPlace: 'Lucknow, Uttar Pradesh',
    currentPlace: 'Lucknow, Uttar Pradesh',
    occupation: 'Retired Bank Manager',
    gender: 'male',
    relationship: 'maternal-uncle',
    bio: "Ramdas's elder brother. A disciplinarian and avid reader who never missed writing letters to relatives.",
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Lucknow',
    tags: ['elder', 'veteran'],
    side: 'maternal',
    parentIds: ['g0-3', 'g0-4'],
    spouseIds: [],
    generation: 1,
    isAlive: false,
    networkGroup: 'extended',
    milestones: [
      { id: 'me4', title: 'Born in Lucknow', year: 1945, type: 'birth' },
      { id: 'me5', title: 'Joined State Bank of India', year: 1967, type: 'career' },
      { id: 'me6', title: 'Retired as Branch Manager', year: 2005, type: 'career' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-06-01',
  },

  // ── Affiliated Family: Rao Family (Priya's natal family) ───────────────────
  // Connected through Priya Rao (g2-2, who married Vikram Sharma g2-1)
  // Priya's father
  {
    id: 'aff-rao-1',
    name: 'Shyam Rao',
    birthYear: 1948,
    deathYear: 2020,
    birthPlace: 'Hyderabad, Telangana',
    currentPlace: 'Hyderabad, Telangana',
    occupation: 'Retired IAS Officer',
    gender: 'male',
    relationship: 'father-in-law',
    bio: "Priya's father. A distinguished IAS officer who served in Maharashtra cadre. Known for integrity and sharp wit.",
    religion: 'Hindu',
    nativeLanguage: 'Telugu',
    hometown: 'Hyderabad',
    tags: ['elder', 'patriarch', 'veteran'],
    side: 'spouse',
    parentIds: [],
    spouseIds: ['aff-rao-2'],
    generation: 1,
    isAlive: false,
    networkGroup: 'affiliated',
    affiliatedFamilyId: 'rao-family',
    affiliatedFamilyName: 'Rao Family',
    affiliatedJunctionId: 'g2-2',
    milestones: [
      { id: 'ma1', title: 'Born in Hyderabad', year: 1948, type: 'birth' },
      { id: 'ma2', title: 'Joined IAS', year: 1972, type: 'career' },
      { id: 'ma3', title: 'Married Usha', year: 1974, type: 'marriage' },
      { id: 'ma4', title: 'Retired from IAS', year: 2008, type: 'career' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-06-01',
  },
  // Priya's mother
  {
    id: 'aff-rao-2',
    name: 'Usha Rao',
    birthYear: 1952,
    birthPlace: 'Visakhapatnam, Andhra Pradesh',
    currentPlace: 'Hyderabad, Telangana',
    occupation: 'Classical Musician (Carnatic Vocalist)',
    gender: 'female',
    relationship: 'mother-in-law',
    bio: "Priya's mother. A renowned Carnatic vocalist who has trained over 300 students. Her morning ragas echo through the whole colony.",
    religion: 'Hindu',
    nativeLanguage: 'Telugu',
    hometown: 'Hyderabad',
    tags: ['elder', 'matriarch', 'artist'],
    side: 'spouse',
    parentIds: [],
    spouseIds: ['aff-rao-1'],
    generation: 1,
    isAlive: true,
    networkGroup: 'affiliated',
    affiliatedFamilyId: 'rao-family',
    affiliatedFamilyName: 'Rao Family',
    affiliatedJunctionId: 'g2-2',
    milestones: [
      { id: 'ma5', title: 'Born in Visakhapatnam', year: 1952, type: 'birth' },
      { id: 'ma6', title: 'Performed at Thyagaraja Aradhana', year: 1985, type: 'achievement' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-06-01',
  },
  // Priya's brother
  {
    id: 'aff-rao-3',
    name: 'Nitin Rao',
    birthYear: 1976,
    birthPlace: 'Hyderabad, Telangana',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'Startup Founder (EdTech)',
    gender: 'male',
    relationship: 'brother-in-law',
    bio: "Priya's brother. Co-founded an EdTech platform serving 200K students. Frequent speaker at TEDx events.",
    religion: 'Hindu',
    nativeLanguage: 'Telugu',
    hometown: 'Hyderabad',
    tags: ['scholar', 'youth'],
    side: 'spouse',
    parentIds: ['aff-rao-1', 'aff-rao-2'],
    spouseIds: [],
    generation: 2,
    isAlive: true,
    networkGroup: 'affiliated',
    affiliatedFamilyId: 'rao-family',
    affiliatedFamilyName: 'Rao Family',
    affiliatedJunctionId: 'g2-2',
    milestones: [
      { id: 'ma7', title: 'Born in Hyderabad', year: 1976, type: 'birth' },
      { id: 'ma8', title: 'Founded LearnBridge EdTech', year: 2012, type: 'career' },
      { id: 'ma9', title: 'TEDx Bangalore Speaker', year: 2019, type: 'achievement' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-06-01',
  },

  // ── Extended Family: Sharma Branch (Paternal) — more cousins & relatives ───

  // Suresh's younger brother Dinesh branch
  { id: 'ext-4', name: 'Dinesh Kumar Sharma', birthYear: 1952, birthPlace: 'Varanasi, UP', currentPlace: 'Jaipur, Rajasthan', occupation: 'Retired Railway Engineer', gender: 'male', relationship: 'great-uncle', bio: "Suresh's younger brother. Built railways across Rajasthan.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Varanasi', tags: ['elder'], side: 'paternal', parentIds: ['g0-1', 'g0-2'], spouseIds: ['ext-5'], generation: 1, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex4m1', title: 'Born in Varanasi', year: 1952, type: 'birth' }, { id: 'ex4m2', title: 'Married Kamla Devi', year: 1977, type: 'marriage' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-5', name: 'Kamla Sharma', birthYear: 1955, birthPlace: 'Jaipur, Rajasthan', currentPlace: 'Jaipur, Rajasthan', occupation: 'Homemaker', gender: 'female', relationship: 'great-aunt', bio: "Dinesh's wife. Known for her exceptional rajasthani cuisine.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Jaipur', tags: ['elder'], side: 'paternal', parentIds: [], spouseIds: ['ext-4'], generation: 1, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex5m1', title: 'Born in Jaipur', year: 1955, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-6', name: 'Ramesh Sharma', birthYear: 1978, birthPlace: 'Jaipur, Rajasthan', currentPlace: 'Jaipur, Rajasthan', occupation: 'Hotelier', gender: 'male', relationship: 'first-cousin-once-removed', bio: 'Dinesh & Kamla son. Runs a heritage hotel in old Jaipur.', gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Jaipur', tags: [], side: 'paternal', parentIds: ['ext-4', 'ext-5'], spouseIds: ['ext-7'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex6m1', title: 'Born in Jaipur', year: 1978, type: 'birth' }, { id: 'ex6m2', title: 'Opened Heritage Hotel', year: 2010, type: 'career' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-7', name: 'Meena Sharma', birthYear: 1980, birthPlace: 'Udaipur, Rajasthan', currentPlace: 'Jaipur, Rajasthan', occupation: 'Interior Designer', gender: 'female', relationship: 'first-cousin-once-removed', bio: "Ramesh's wife. Designed 3 heritage hotels.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Udaipur', tags: [], side: 'paternal', parentIds: [], spouseIds: ['ext-6'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex7m1', title: 'Born in Udaipur', year: 1980, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-8', name: 'Sneha Sharma', birthYear: 2005, birthPlace: 'Jaipur, Rajasthan', currentPlace: 'Jaipur, Rajasthan', occupation: 'Student (Architecture)', gender: 'female', relationship: 'second-cousin', bio: 'Ramesh & Meena daughter. Studying architecture at MNIT Jaipur.', gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Jaipur', tags: ['youth'], side: 'paternal', parentIds: ['ext-6', 'ext-7'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex8m1', title: 'Born in Jaipur', year: 2005, type: 'birth' }, { id: 'ex8m2', title: 'Admitted to MNIT Architecture', year: 2023, type: 'education' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-9', name: 'Ankur Sharma', birthYear: 2008, birthPlace: 'Jaipur, Rajasthan', currentPlace: 'Jaipur, Rajasthan', occupation: 'School Student', gender: 'male', relationship: 'second-cousin', bio: 'Ramesh & Meena son. Chess prodigy.', gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Jaipur', tags: ['youth'], side: 'paternal', parentIds: ['ext-6', 'ext-7'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex9m1', title: 'Born in Jaipur', year: 2008, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },

  // Suresh's youngest sister Sunita branch
  { id: 'ext-10', name: 'Sunita Sharma', birthYear: 1958, birthPlace: 'Varanasi, UP', currentPlace: 'Delhi, NCR', occupation: 'Retired Government Teacher', gender: 'female', relationship: 'great-aunt', bio: "Suresh's youngest sister. Retired from Delhi govt schools.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Varanasi', tags: ['elder'], side: 'paternal', parentIds: ['g0-1', 'g0-2'], spouseIds: ['ext-11'], generation: 1, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex10m1', title: 'Born in Varanasi', year: 1958, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-11', name: 'Rajendra Tiwari', birthYear: 1955, birthPlace: 'Delhi, NCR', currentPlace: 'Delhi, NCR', occupation: 'Retired IRS Officer', gender: 'male', relationship: 'great-uncle', bio: "Sunita's husband. Retired from Income Tax Department.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Delhi', tags: ['elder'], side: 'paternal', parentIds: [], spouseIds: ['ext-10'], generation: 1, isAlive: false, networkGroup: 'extended', milestones: [{ id: 'ex11m1', title: 'Born in Delhi', year: 1955, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-12', name: 'Abhishek Tiwari', birthYear: 1982, birthPlace: 'Delhi, NCR', currentPlace: 'Gurugram, Haryana', occupation: 'Software Engineer (Google)', gender: 'male', relationship: 'first-cousin-once-removed', bio: 'Sunita & Rajendra son. Works at Google India.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Delhi', tags: ['scholar'], side: 'paternal', parentIds: ['ext-10', 'ext-11'], spouseIds: ['ext-13'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex12m1', title: 'Born in Delhi', year: 1982, type: 'birth' }, { id: 'ex12m2', title: 'Joined Google', year: 2010, type: 'career' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-13', name: 'Pooja Tiwari', birthYear: 1984, birthPlace: 'Noida, UP', currentPlace: 'Gurugram, Haryana', occupation: 'UX Designer', gender: 'female', relationship: 'first-cousin-once-removed', bio: "Abhishek's wife. Senior UX Designer at a fintech startup.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Noida', tags: [], side: 'paternal', parentIds: [], spouseIds: ['ext-12'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex13m1', title: 'Born in Noida', year: 1984, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-14', name: 'Aanya Tiwari', birthYear: 2012, birthPlace: 'Gurugram, Haryana', currentPlace: 'Gurugram, Haryana', occupation: 'School Student', gender: 'female', relationship: 'second-cousin', bio: 'Abhishek & Pooja daughter. National-level swimming champion.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Gurugram', tags: ['youth'], side: 'paternal', parentIds: ['ext-12', 'ext-13'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex14m1', title: 'Born in Gurugram', year: 2012, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-15', name: 'Vikas Tiwari', birthYear: 1986, birthPlace: 'Delhi, NCR', currentPlace: 'Delhi, NCR', occupation: 'Journalist (NDTV)', gender: 'male', relationship: 'first-cousin-once-removed', bio: 'Sunita & Rajendra younger son. Political journalist.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Delhi', tags: [], side: 'paternal', parentIds: ['ext-10', 'ext-11'], spouseIds: [], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex15m1', title: 'Born in Delhi', year: 1986, type: 'birth' }, { id: 'ex15m2', title: 'Joined NDTV', year: 2012, type: 'career' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },

  // Vikram's uncle Harishchandra branch
  { id: 'ext-16', name: 'Harishchandra Sharma', birthYear: 1950, deathYear: 2022, birthPlace: 'Nagpur, Maharashtra', currentPlace: 'Nagpur, Maharashtra', occupation: 'Retired Professor', gender: 'male', relationship: 'great-uncle', bio: "Vikram's father's elder brother. Professor of History at Nagpur University.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Nagpur', tags: ['elder', 'scholar'], side: 'paternal', parentIds: ['g0-1', 'g0-2'], spouseIds: ['ext-17'], generation: 1, isAlive: false, networkGroup: 'extended', milestones: [{ id: 'ex16m1', title: 'Born in Nagpur', year: 1950, type: 'birth' }, { id: 'ex16m2', title: 'Joined Nagpur University', year: 1975, type: 'career' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-17', name: 'Vimla Sharma', birthYear: 1953, birthPlace: 'Amravati, Maharashtra', currentPlace: 'Nagpur, Maharashtra', occupation: 'Homemaker', gender: 'female', relationship: 'great-aunt', bio: "Harishchandra's wife. Famous for her classical Hindustani singing.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Amravati', tags: ['elder', 'artist'], side: 'paternal', parentIds: [], spouseIds: ['ext-16'], generation: 1, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex17m1', title: 'Born in Amravati', year: 1953, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-18', name: 'Nikhil Sharma', birthYear: 1980, birthPlace: 'Nagpur, Maharashtra', currentPlace: 'Nagpur, Maharashtra', occupation: 'Advocate (High Court)', gender: 'male', relationship: 'first-cousin-once-removed', bio: 'Harishchandra & Vimla son. Senior advocate at Nagpur High Court.', gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Nagpur', tags: ['scholar'], side: 'paternal', parentIds: ['ext-16', 'ext-17'], spouseIds: ['ext-19'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex18m1', title: 'Born in Nagpur', year: 1980, type: 'birth' }, { id: 'ex18m2', title: 'Enrolled at High Court Bar', year: 2008, type: 'career' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-19', name: 'Manasi Sharma', birthYear: 1982, birthPlace: 'Pune, Maharashtra', currentPlace: 'Nagpur, Maharashtra', occupation: 'Doctor (Gynaecologist)', gender: 'female', relationship: 'first-cousin-once-removed', bio: "Nikhil's wife. Senior gynaecologist at AIIMS Nagpur.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Marathi', hometown: 'Pune', tags: ['scholar'], side: 'paternal', parentIds: [], spouseIds: ['ext-18'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex19m1', title: 'Born in Pune', year: 1982, type: 'birth' }, { id: 'ex19m2', title: 'Joined AIIMS Nagpur', year: 2012, type: 'career' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-20', name: 'Samarth Sharma', birthYear: 2010, birthPlace: 'Nagpur, Maharashtra', currentPlace: 'Nagpur, Maharashtra', occupation: 'School Student', gender: 'male', relationship: 'second-cousin', bio: 'Nikhil & Manasi son. Robotics enthusiast.', gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Nagpur', tags: ['youth'], side: 'paternal', parentIds: ['ext-18', 'ext-19'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex20m1', title: 'Born in Nagpur', year: 2010, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-21', name: 'Gauri Sharma', birthYear: 1984, birthPlace: 'Nagpur, Maharashtra', currentPlace: 'Mumbai, Maharashtra', occupation: 'Fashion Photographer', gender: 'female', relationship: 'first-cousin-once-removed', bio: 'Harishchandra & Vimla daughter. Featured in Vogue India twice.', gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Nagpur', tags: ['artist'], side: 'paternal', parentIds: ['ext-16', 'ext-17'], spouseIds: [], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex21m1', title: 'Born in Nagpur', year: 1984, type: 'birth' }, { id: 'ex21m2', title: 'Published in Vogue India', year: 2018, type: 'achievement' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },

  // Mohan Sharma's children (ext-1 & ext-2)
  { id: 'ext-22', name: 'Prakash Sharma', birthYear: 1996, birthPlace: 'Nagpur, Maharashtra', currentPlace: 'Nagpur, Maharashtra', occupation: 'Civil Contractor', gender: 'male', relationship: 'second-cousin', bio: "Mohan & Sudha's son. Joined family contracting business.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Nagpur', tags: [], side: 'paternal', parentIds: ['ext-1', 'ext-2'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex22m1', title: 'Born in Nagpur', year: 1996, type: 'birth' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },
  { id: 'ext-23', name: 'Prachi Sharma', birthYear: 1999, birthPlace: 'Nagpur, Maharashtra', currentPlace: 'Pune, Maharashtra', occupation: 'MBA Student', gender: 'female', relationship: 'second-cousin', bio: "Mohan & Sudha's daughter. Pursuing MBA at SIBM Pune.", gotra: 'Bharadwaj', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Nagpur', tags: ['youth', 'scholar'], side: 'paternal', parentIds: ['ext-1', 'ext-2'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex23m1', title: 'Born in Nagpur', year: 1999, type: 'birth' }, { id: 'ex23m2', title: 'Admitted to SIBM Pune', year: 2022, type: 'education' }], addedBy: 'Rahul Sharma', addedAt: '2024-07-01' },

  // ── Extended Family: Mishra Branch (Maternal) ─────────────────────────────

  // Ramdas's sister Savita branch
  { id: 'ext-24', name: 'Savita Mishra', birthYear: 1948, birthPlace: 'Lucknow, UP', currentPlace: 'Lucknow, UP', occupation: 'Retired Principal', gender: 'female', relationship: 'maternal-great-aunt', bio: "Ramdas's elder sister. Principal of a prestigious girls' school in Lucknow for 30 years.", gotra: 'Kashyap', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Lucknow', tags: ['elder', 'scholar'], side: 'maternal', parentIds: ['g0-3', 'g0-4'], spouseIds: ['ext-25'], generation: 1, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex24m1', title: 'Born in Lucknow', year: 1948, type: 'birth' }, { id: 'ex24m2', title: 'Became Principal', year: 1985, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-25', name: 'Ramakant Dubey', birthYear: 1945, deathYear: 2015, birthPlace: 'Varanasi, UP', currentPlace: 'Lucknow, UP', occupation: 'Retired Professor', gender: 'male', relationship: 'maternal-great-uncle', bio: "Savita's husband. Sanskrit professor at Lucknow University.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Varanasi', tags: ['elder', 'scholar'], side: 'maternal', parentIds: [], spouseIds: ['ext-24'], generation: 1, isAlive: false, networkGroup: 'extended', milestones: [{ id: 'ex25m1', title: 'Born in Varanasi', year: 1945, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-26', name: 'Manish Dubey', birthYear: 1974, birthPlace: 'Lucknow, UP', currentPlace: 'Lucknow, UP', occupation: 'Chartered Accountant', gender: 'male', relationship: 'maternal-second-cousin', bio: 'Savita & Ramakant son. Partner at a CA firm.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Lucknow', tags: [], side: 'maternal', parentIds: ['ext-24', 'ext-25'], spouseIds: ['ext-27'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex26m1', title: 'Born in Lucknow', year: 1974, type: 'birth' }, { id: 'ex26m2', title: 'Founded Dubey & Associates', year: 2005, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-27', name: 'Shweta Dubey', birthYear: 1976, birthPlace: 'Kanpur, UP', currentPlace: 'Lucknow, UP', occupation: 'Doctor (Paediatrician)', gender: 'female', relationship: 'maternal-second-cousin', bio: "Manish's wife. Senior paediatrician. Has treated thousands of children across UP.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Kanpur', tags: ['scholar'], side: 'maternal', parentIds: [], spouseIds: ['ext-26'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex27m1', title: 'Born in Kanpur', year: 1976, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-28', name: 'Tanvi Dubey', birthYear: 2002, birthPlace: 'Lucknow, UP', currentPlace: 'Mumbai, Maharashtra', occupation: 'Film Student (FTII)', gender: 'female', relationship: 'third-cousin', bio: 'Manish & Shweta daughter. Studying direction at FTII Pune.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Lucknow', tags: ['youth', 'artist'], side: 'maternal', parentIds: ['ext-26', 'ext-27'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex28m1', title: 'Born in Lucknow', year: 2002, type: 'birth' }, { id: 'ex28m2', title: 'Admitted to FTII', year: 2022, type: 'education' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-29', name: 'Rohan Dubey', birthYear: 2005, birthPlace: 'Lucknow, UP', currentPlace: 'Lucknow, UP', occupation: 'School Student', gender: 'male', relationship: 'third-cousin', bio: 'Manish & Shweta son. State-level swimmer.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Lucknow', tags: ['youth'], side: 'maternal', parentIds: ['ext-26', 'ext-27'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex29m1', title: 'Born in Lucknow', year: 2005, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },

  // Ashok Mishra's siblings branch (Ashok is g2-5)
  { id: 'ext-30', name: 'Sanjay Mishra', birthYear: 1974, birthPlace: 'Pune, Maharashtra', currentPlace: 'Hyderabad, Telangana', occupation: 'Senior Manager (TCS)', gender: 'male', relationship: 'maternal-uncle', bio: "Ashok's elder brother. Works in TCS Hyderabad's banking vertical.", gotra: 'Kashyap', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Pune', tags: [], side: 'maternal', parentIds: ['g1-3', 'g1-4'], spouseIds: ['ext-31'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex30m1', title: 'Born in Pune', year: 1974, type: 'birth' }, { id: 'ex30m2', title: 'Joined TCS', year: 2000, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-31', name: 'Jayanti Mishra', birthYear: 1977, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'Businesswoman (Boutique)', gender: 'female', relationship: 'maternal-aunt', bio: "Sanjay's wife. Runs a successful saree boutique.", gotra: 'Kashyap', religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Hyderabad', tags: [], side: 'maternal', parentIds: [], spouseIds: ['ext-30'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex31m1', title: 'Born in Hyderabad', year: 1977, type: 'birth' }, { id: 'ex31m2', title: 'Opened Jayanti Sarees', year: 2008, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-32', name: 'Aditya Mishra', birthYear: 2001, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'Software Developer', gender: 'male', relationship: 'second-cousin', bio: 'Sanjay & Jayanti son. Full-stack developer at a startup.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Hyderabad', tags: ['youth', 'scholar'], side: 'maternal', parentIds: ['ext-30', 'ext-31'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex32m1', title: 'Born in Hyderabad', year: 2001, type: 'birth' }, { id: 'ex32m2', title: 'Joined tech startup', year: 2024, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-33', name: 'Ishita Mishra', birthYear: 2004, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'Student (B.Pharm)', gender: 'female', relationship: 'second-cousin', bio: 'Sanjay & Jayanti daughter. Aspiring pharmacologist.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Hyderabad', tags: ['youth'], side: 'maternal', parentIds: ['ext-30', 'ext-31'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex33m1', title: 'Born in Hyderabad', year: 2004, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-34', name: 'Rekha Mishra', birthYear: 1980, birthPlace: 'Pune, Maharashtra', currentPlace: 'Bengaluru, Karnataka', occupation: 'NGO Founder', gender: 'female', relationship: 'maternal-aunt', bio: "Ashok's younger sister. Founded Swayam NGO for women's education.", gotra: 'Kashyap', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Pune', tags: ['scholar'], side: 'maternal', parentIds: ['g1-3', 'g1-4'], spouseIds: ['ext-35'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex34m1', title: 'Born in Pune', year: 1980, type: 'birth' }, { id: 'ex34m2', title: 'Founded Swayam NGO', year: 2009, type: 'achievement' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-35', name: 'Vijay Kulkarni', birthYear: 1977, birthPlace: 'Bengaluru, Karnataka', currentPlace: 'Bengaluru, Karnataka', occupation: 'Architect', gender: 'male', relationship: 'maternal-uncle', bio: "Rekha's husband. Renowned green-architecture designer in Bengaluru.", religion: 'Hindu', nativeLanguage: 'Kannada', hometown: 'Bengaluru', tags: [], side: 'maternal', parentIds: [], spouseIds: ['ext-34'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex35m1', title: 'Born in Bengaluru', year: 1977, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-36', name: 'Neel Kulkarni', birthYear: 2007, birthPlace: 'Bengaluru, Karnataka', currentPlace: 'Bengaluru, Karnataka', occupation: 'School Student', gender: 'male', relationship: 'second-cousin', bio: 'Rekha & Vijay son. Coding enthusiast.', religion: 'Hindu', nativeLanguage: 'Kannada', hometown: 'Bengaluru', tags: ['youth'], side: 'maternal', parentIds: ['ext-34', 'ext-35'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex36m1', title: 'Born in Bengaluru', year: 2007, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-37', name: 'Diya Kulkarni', birthYear: 2010, birthPlace: 'Bengaluru, Karnataka', currentPlace: 'Bengaluru, Karnataka', occupation: 'School Student', gender: 'female', relationship: 'second-cousin', bio: 'Rekha & Vijay daughter. State-level Bharatanatyam performer.', religion: 'Hindu', nativeLanguage: 'Kannada', hometown: 'Bengaluru', tags: ['youth', 'artist'], side: 'maternal', parentIds: ['ext-34', 'ext-35'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex37m1', title: 'Born in Bengaluru', year: 2010, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },

  // Shivdas Mishra's children (ext-3)
  { id: 'ext-38', name: 'Rahul Mishra', birthYear: 1970, birthPlace: 'Lucknow, UP', currentPlace: 'Lucknow, UP', occupation: 'Doctor (Cardiologist)', gender: 'male', relationship: 'maternal-second-cousin', bio: "Shivdas's son. Senior cardiologist at SGPGI Lucknow.", gotra: 'Kashyap', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Lucknow', tags: ['scholar'], side: 'maternal', parentIds: ['ext-3'], spouseIds: ['ext-39'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex38m1', title: 'Born in Lucknow', year: 1970, type: 'birth' }, { id: 'ex38m2', title: 'Joined SGPGI', year: 2000, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-39', name: 'Seema Mishra', birthYear: 1973, birthPlace: 'Allahabad, UP', currentPlace: 'Lucknow, UP', occupation: 'Professor (Economics)', gender: 'female', relationship: 'maternal-second-cousin', bio: "Rahul Mishra's wife. Economics professor at Lucknow University.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Allahabad', tags: ['scholar'], side: 'maternal', parentIds: [], spouseIds: ['ext-38'], generation: 2, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex39m1', title: 'Born in Allahabad', year: 1973, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'ext-40', name: 'Kartik Mishra', birthYear: 1998, birthPlace: 'Lucknow, UP', currentPlace: 'New Delhi', occupation: 'IAS Officer (Probationer)', gender: 'male', relationship: 'third-cousin', bio: 'Rahul & Seema son. Cleared UPSC 2023 in first attempt. AIR 47.', gotra: 'Kashyap', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Lucknow', tags: ['youth', 'scholar', 'veteran'], side: 'maternal', parentIds: ['ext-38', 'ext-39'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'extended', milestones: [{ id: 'ex40m1', title: 'Born in Lucknow', year: 1998, type: 'birth' }, { id: 'ex40m2', title: 'Cleared UPSC — AIR 47', year: 2023, type: 'achievement' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },

  // ── Affiliated Family: Kapoor Family (Deepak Sharma's wife's family) ────────
  // Connected through Sunita Kapoor who married Deepak Sharma (g2-3)
  { id: 'aff-kap-1', name: 'Mahesh Kapoor', birthYear: 1950, deathYear: 2019, birthPlace: 'Amritsar, Punjab', currentPlace: 'Mumbai, Maharashtra', occupation: 'Retired Textile Businessman', gender: 'male', relationship: 'father-in-law', bio: "Sunita's father. Built a textile empire from one shop in Amritsar to 12 stores across India.", religion: 'Hindu', nativeLanguage: 'Punjabi', hometown: 'Amritsar', tags: ['elder', 'patriarch'], side: 'spouse', parentIds: [], spouseIds: ['aff-kap-2'], generation: 1, isAlive: false, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak1m1', title: 'Born in Amritsar', year: 1950, type: 'birth' }, { id: 'ak1m2', title: 'Founded Kapoor Textiles', year: 1978, type: 'career' }, { id: 'ak1m3', title: 'Married Harpreet', year: 1975, type: 'marriage' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-2', name: 'Harpreet Kapoor', birthYear: 1953, birthPlace: 'Ludhiana, Punjab', currentPlace: 'Mumbai, Maharashtra', occupation: 'Social Worker', gender: 'female', relationship: 'mother-in-law', bio: "Sunita's mother. Runs a free stitching school for underprivileged women in Dharavi.", religion: 'Hindu', nativeLanguage: 'Punjabi', hometown: 'Ludhiana', tags: ['elder', 'matriarch'], side: 'spouse', parentIds: [], spouseIds: ['aff-kap-1'], generation: 1, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak2m1', title: 'Born in Ludhiana', year: 1953, type: 'birth' }, { id: 'ak2m2', title: 'Opened Dharavi Stitching School', year: 2000, type: 'achievement' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-3', name: 'Rajiv Kapoor', birthYear: 1977, birthPlace: 'Mumbai, Maharashtra', currentPlace: 'Mumbai, Maharashtra', occupation: 'Film Producer', gender: 'male', relationship: 'brother-in-law', bio: "Sunita's elder brother. Producer of 3 critically-acclaimed Bollywood films.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Mumbai', tags: ['artist'], side: 'spouse', parentIds: ['aff-kap-1', 'aff-kap-2'], spouseIds: ['aff-kap-4'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak3m1', title: 'Born in Mumbai', year: 1977, type: 'birth' }, { id: 'ak3m2', title: 'Produced first film', year: 2010, type: 'career' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-4', name: 'Divya Kapoor', birthYear: 1980, birthPlace: 'Delhi, NCR', currentPlace: 'Mumbai, Maharashtra', occupation: 'Costume Designer (Bollywood)', gender: 'female', relationship: 'sister-in-law', bio: "Rajiv's wife. National Film Award-winning costume designer.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Delhi', tags: ['artist'], side: 'spouse', parentIds: [], spouseIds: ['aff-kap-3'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak4m1', title: 'Born in Delhi', year: 1980, type: 'birth' }, { id: 'ak4m2', title: 'Won National Film Award', year: 2018, type: 'achievement' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-5', name: 'Kabir Kapoor', birthYear: 2005, birthPlace: 'Mumbai, Maharashtra', currentPlace: 'Mumbai, Maharashtra', occupation: 'Student (Film School)', gender: 'male', relationship: 'nephew-in-law', bio: 'Rajiv & Divya son. Already directing short films at 18.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Mumbai', tags: ['youth', 'artist'], side: 'spouse', parentIds: ['aff-kap-3', 'aff-kap-4'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak5m1', title: 'Born in Mumbai', year: 2005, type: 'birth' }, { id: 'ak5m2', title: 'Short film screened at MAMI', year: 2023, type: 'achievement' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-6', name: 'Zara Kapoor', birthYear: 2008, birthPlace: 'Mumbai, Maharashtra', currentPlace: 'Mumbai, Maharashtra', occupation: 'School Student', gender: 'female', relationship: 'niece-in-law', bio: 'Rajiv & Divya daughter. Passionate about fashion and design.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Mumbai', tags: ['youth'], side: 'spouse', parentIds: ['aff-kap-3', 'aff-kap-4'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak6m1', title: 'Born in Mumbai', year: 2008, type: 'birth' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-7', name: 'Priya Kapoor', birthYear: 1982, birthPlace: 'Mumbai, Maharashtra', currentPlace: 'Singapore', occupation: 'Investment Banker', gender: 'female', relationship: 'sister-in-law', bio: "Sunita's younger sister. VP at Goldman Sachs Singapore. Visits every Diwali.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Mumbai', tags: ['scholar'], side: 'spouse', parentIds: ['aff-kap-1', 'aff-kap-2'], spouseIds: ['aff-kap-8'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak7m1', title: 'Born in Mumbai', year: 1982, type: 'birth' }, { id: 'ak7m2', title: 'Joined Goldman Sachs Singapore', year: 2012, type: 'career' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-8', name: 'Wei Chen', birthYear: 1980, birthPlace: 'Shanghai, China', currentPlace: 'Singapore', occupation: 'Tech Entrepreneur', gender: 'male', relationship: 'brother-in-law', bio: "Priya Kapoor's husband. Co-founded a Singapore-based AI startup.", religion: 'Buddhist', nativeLanguage: 'Mandarin', hometown: 'Shanghai', tags: [], side: 'spouse', parentIds: [], spouseIds: ['aff-kap-7'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak8m1', title: 'Born in Shanghai', year: 1980, type: 'birth' }, { id: 'ak8m2', title: 'Founded AI startup in Singapore', year: 2015, type: 'career' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-9', name: 'Maya Chen', birthYear: 2010, birthPlace: 'Singapore', currentPlace: 'Singapore', occupation: 'School Student', gender: 'female', relationship: 'niece-in-law', bio: 'Priya & Wei daughter. Fluent in Hindi, English and Mandarin.', religion: 'Hindu', nativeLanguage: 'English', hometown: 'Singapore', tags: ['youth'], side: 'spouse', parentIds: ['aff-kap-7', 'aff-kap-8'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak9m1', title: 'Born in Singapore', year: 2010, type: 'birth' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-10', name: 'Aryan Kapoor', birthYear: 1985, birthPlace: 'Mumbai, Maharashtra', currentPlace: 'Mumbai, Maharashtra', occupation: 'Textile Businessman', gender: 'male', relationship: 'nephew-in-law', bio: "Mahesh's nephew. Took over Kapoor Textiles after Mahesh's passing.", religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Mumbai', tags: [], side: 'spouse', parentIds: [], spouseIds: ['aff-kap-11'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak10m1', title: 'Born in Mumbai', year: 1985, type: 'birth' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-11', name: 'Nisha Kapoor', birthYear: 1987, birthPlace: 'Ahmedabad, Gujarat', currentPlace: 'Mumbai, Maharashtra', occupation: 'Nutritionist', gender: 'female', relationship: 'niece-in-law', bio: "Aryan's wife. Certified nutritionist and popular wellness blogger.", religion: 'Hindu', nativeLanguage: 'Gujarati', hometown: 'Ahmedabad', tags: [], side: 'spouse', parentIds: [], spouseIds: ['aff-kap-10'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak11m1', title: 'Born in Ahmedabad', year: 1987, type: 'birth' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
  { id: 'aff-kap-12', name: 'Dev Kapoor', birthYear: 2012, birthPlace: 'Mumbai, Maharashtra', currentPlace: 'Mumbai, Maharashtra', occupation: 'School Student', gender: 'male', relationship: 'nephew-in-law', bio: 'Aryan & Nisha son. Cricket player.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Mumbai', tags: ['youth'], side: 'spouse', parentIds: ['aff-kap-10', 'aff-kap-11'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak12m1', title: 'Born in Mumbai', year: 2012, type: 'birth' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },

  // ── Affiliated Family: Iyer Family (Kavitha Mishra's natal family) ───────────
  // Kavitha Iyer married Ashok Mishra (g2-5); junction is g2-5
  { id: 'aff-iye-1', name: 'Venkataraman Iyer', birthYear: 1952, deathYear: 2021, birthPlace: 'Chennai, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'Retired Judge (Madras High Court)', gender: 'male', relationship: 'father-in-law', bio: "Kavitha's father. Former judge at Madras High Court. Known for landmark judgments on property rights.", religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Chennai', tags: ['elder', 'patriarch', 'scholar'], side: 'spouse', parentIds: [], spouseIds: ['aff-iye-2'], generation: 1, isAlive: false, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai1m1', title: 'Born in Chennai', year: 1952, type: 'birth' }, { id: 'ai1m2', title: 'Appointed to Madras High Court', year: 1990, type: 'career' }, { id: 'ai1m3', title: 'Married Meenakshi', year: 1978, type: 'marriage' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-2', name: 'Meenakshi Iyer', birthYear: 1955, birthPlace: 'Madurai, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'Classical Veena Player', gender: 'female', relationship: 'mother-in-law', bio: "Kavitha's mother. Performed at Thyagaraja Aradhana for 40 consecutive years.", religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Madurai', tags: ['elder', 'matriarch', 'artist'], side: 'spouse', parentIds: [], spouseIds: ['aff-iye-1'], generation: 1, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai2m1', title: 'Born in Madurai', year: 1955, type: 'birth' }, { id: 'ai2m2', title: 'First performance at Thyagaraja Aradhana', year: 1982, type: 'achievement' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-3', name: 'Suresh Iyer', birthYear: 1980, birthPlace: 'Chennai, Tamil Nadu', currentPlace: 'San Francisco, USA', occupation: 'Software Engineer (Meta)', gender: 'male', relationship: 'brother-in-law', bio: "Kavitha's brother. Senior engineer at Meta. US resident since 2008.", religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Chennai', tags: ['scholar'], side: 'spouse', parentIds: ['aff-iye-1', 'aff-iye-2'], spouseIds: ['aff-iye-4'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai3m1', title: 'Born in Chennai', year: 1980, type: 'birth' }, { id: 'ai3m2', title: 'Joined Meta', year: 2010, type: 'career' }, { id: 'ai3m3', title: 'Moved to San Francisco', year: 2008, type: 'relocation' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-4', name: 'Jennifer Iyer', birthYear: 1982, birthPlace: 'Austin, Texas, USA', currentPlace: 'San Francisco, USA', occupation: 'Data Scientist (Google)', gender: 'female', relationship: 'sister-in-law', bio: "Suresh's wife. PhD in Machine Learning from Stanford. Works at Google Brain.", religion: 'Christian', nativeLanguage: 'English', hometown: 'Austin, TX', tags: ['scholar'], side: 'spouse', parentIds: [], spouseIds: ['aff-iye-3'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai4m1', title: 'Born in Austin', year: 1982, type: 'birth' }, { id: 'ai4m2', title: 'PhD from Stanford', year: 2010, type: 'education' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-5', name: 'Arjun Iyer', birthYear: 2009, birthPlace: 'San Francisco, USA', currentPlace: 'San Francisco, USA', occupation: 'School Student', gender: 'male', relationship: 'nephew-in-law', bio: 'Suresh & Jennifer son. Speaks Tamil, Hindi and English. Loves cricket.', religion: 'Hindu', nativeLanguage: 'English', hometown: 'San Francisco', tags: ['youth'], side: 'spouse', parentIds: ['aff-iye-3', 'aff-iye-4'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai5m1', title: 'Born in San Francisco', year: 2009, type: 'birth' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-6', name: 'Priya Iyer', birthYear: 2012, birthPlace: 'San Francisco, USA', currentPlace: 'San Francisco, USA', occupation: 'School Student', gender: 'female', relationship: 'niece-in-law', bio: 'Suresh & Jennifer daughter. Has performed Bharatanatyam at a US cultural fest.', religion: 'Hindu', nativeLanguage: 'English', hometown: 'San Francisco', tags: ['youth', 'artist'], side: 'spouse', parentIds: ['aff-iye-3', 'aff-iye-4'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai6m1', title: 'Born in San Francisco', year: 2012, type: 'birth' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-7', name: 'Lakshmi Iyer', birthYear: 1984, birthPlace: 'Chennai, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'Carnatic Singer', gender: 'female', relationship: 'sister-in-law', bio: "Kavitha's younger sister. Professional Carnatic vocalist, disciple of MS Subbulakshmi school.", religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Chennai', tags: ['artist'], side: 'spouse', parentIds: ['aff-iye-1', 'aff-iye-2'], spouseIds: ['aff-iye-8'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai7m1', title: 'Born in Chennai', year: 1984, type: 'birth' }, { id: 'ai7m2', title: 'Performed at Music Academy Chennai', year: 2015, type: 'achievement' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-8', name: 'Srinivas Raman', birthYear: 1981, birthPlace: 'Coimbatore, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'Mridangam Maestro', gender: 'male', relationship: 'brother-in-law', bio: "Lakshmi's husband. Accompanies leading Carnatic vocalists across the world.", religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Coimbatore', tags: ['artist'], side: 'spouse', parentIds: [], spouseIds: ['aff-iye-7'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai8m1', title: 'Born in Coimbatore', year: 1981, type: 'birth' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-9', name: 'Krishnapriya Raman', birthYear: 2010, birthPlace: 'Chennai, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'School Student', gender: 'female', relationship: 'niece-in-law', bio: 'Lakshmi & Srinivas daughter. Already learning Carnatic violin.', religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Chennai', tags: ['youth', 'artist'], side: 'spouse', parentIds: ['aff-iye-7', 'aff-iye-8'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai9m1', title: 'Born in Chennai', year: 2010, type: 'birth' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-10', name: 'Vignesh Iyer', birthYear: 1978, birthPlace: 'Chennai, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'Oncologist (AIIMS Chennai)', gender: 'male', relationship: 'brother-in-law', bio: "Kavitha's elder brother. Renowned oncologist.", religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Chennai', tags: ['scholar'], side: 'spouse', parentIds: ['aff-iye-1', 'aff-iye-2'], spouseIds: ['aff-iye-11'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai10m1', title: 'Born in Chennai', year: 1978, type: 'birth' }, { id: 'ai10m2', title: 'Joined AIIMS Chennai', year: 2008, type: 'career' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-11', name: 'Deepa Iyer', birthYear: 1980, birthPlace: 'Thiruvananthapuram, Kerala', currentPlace: 'Chennai, Tamil Nadu', occupation: 'Ophthalmologist', gender: 'female', relationship: 'sister-in-law', bio: "Vignesh's wife. Eye surgeon running a free camp for rural patients.", religion: 'Hindu', nativeLanguage: 'Malayalam', hometown: 'Thiruvananthapuram', tags: ['scholar'], side: 'spouse', parentIds: [], spouseIds: ['aff-iye-10'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai11m1', title: 'Born in Thiruvananthapuram', year: 1980, type: 'birth' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-12', name: 'Siddharth Iyer', birthYear: 2007, birthPlace: 'Chennai, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'School Student', gender: 'male', relationship: 'nephew-in-law', bio: 'Vignesh & Deepa son. State chess champion.', religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Chennai', tags: ['youth'], side: 'spouse', parentIds: ['aff-iye-10', 'aff-iye-11'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai12m1', title: 'Born in Chennai', year: 2007, type: 'birth' }, { id: 'ai12m2', title: 'Won State Chess Championship', year: 2023, type: 'achievement' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-iye-13', name: 'Ananya Iyer', birthYear: 2010, birthPlace: 'Chennai, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'School Student', gender: 'female', relationship: 'niece-in-law', bio: 'Vignesh & Deepa daughter. Bharatanatyam prodigy.', religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Chennai', tags: ['youth', 'artist'], side: 'spouse', parentIds: ['aff-iye-10', 'aff-iye-11'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai13m1', title: 'Born in Chennai', year: 2010, type: 'birth' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },

  // ── Affiliated Family: Nitin Rao's spouse family (from existing Rao branch) ─
  // Nitin Rao (aff-rao-3) is married — adding his wife's family (Mehta Family)
  // Connected through Nitin Rao who is Priya's brother, junction = g2-2 (Priya Sharma)
  { id: 'aff-meh-1', name: 'Sudhir Mehta', birthYear: 1950, birthPlace: 'Ahmedabad, Gujarat', currentPlace: 'Ahmedabad, Gujarat', occupation: 'Retired Industrialist', gender: 'male', relationship: 'father-in-law (extended)', bio: "Nitin Rao's father-in-law. Built a chemical manufacturing empire in Gujarat.", religion: 'Hindu', nativeLanguage: 'Gujarati', hometown: 'Ahmedabad', tags: ['elder', 'patriarch'], side: 'spouse', parentIds: [], spouseIds: ['aff-meh-2'], generation: 1, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am1m1', title: 'Born in Ahmedabad', year: 1950, type: 'birth' }, { id: 'am1m2', title: 'Founded Mehta Chemicals', year: 1980, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-2', name: 'Hansa Mehta', birthYear: 1953, birthPlace: 'Surat, Gujarat', currentPlace: 'Ahmedabad, Gujarat', occupation: 'Homemaker & Philanthropist', gender: 'female', relationship: 'mother-in-law (extended)', bio: "Nitin's mother-in-law. Runs a school for special needs children in Ahmedabad.", religion: 'Hindu', nativeLanguage: 'Gujarati', hometown: 'Surat', tags: ['elder', 'matriarch'], side: 'spouse', parentIds: [], spouseIds: ['aff-meh-1'], generation: 1, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am2m1', title: 'Born in Surat', year: 1953, type: 'birth' }, { id: 'am2m2', title: 'Opened special needs school', year: 2002, type: 'achievement' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-3', name: 'Riya Mehta', birthYear: 1979, birthPlace: 'Ahmedabad, Gujarat', currentPlace: 'Bengaluru, Karnataka', occupation: 'Entrepreneur (EdTech)', gender: 'female', relationship: 'sister-in-law (extended)', bio: "Nitin Rao's wife. Co-founded LearnBridge with him. CFO of the company.", religion: 'Hindu', nativeLanguage: 'Gujarati', hometown: 'Ahmedabad', tags: ['scholar'], side: 'spouse', parentIds: ['aff-meh-1', 'aff-meh-2'], spouseIds: ['aff-rao-3'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am3m1', title: 'Born in Ahmedabad', year: 1979, type: 'birth' }, { id: 'am3m2', title: 'Co-founded LearnBridge', year: 2012, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-4', name: 'Vivaan Mehta-Rao', birthYear: 2006, birthPlace: 'Bengaluru, Karnataka', currentPlace: 'Bengaluru, Karnataka', occupation: 'School Student', gender: 'male', relationship: 'nephew (extended)', bio: 'Nitin & Riya son. Coding competitions winner.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Bengaluru', tags: ['youth', 'scholar'], side: 'spouse', parentIds: ['aff-rao-3', 'aff-meh-3'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am4m1', title: 'Born in Bengaluru', year: 2006, type: 'birth' }, { id: 'am4m2', title: 'Won National Coding Olympiad', year: 2023, type: 'achievement' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-5', name: 'Kiara Mehta-Rao', birthYear: 2009, birthPlace: 'Bengaluru, Karnataka', currentPlace: 'Bengaluru, Karnataka', occupation: 'School Student', gender: 'female', relationship: 'niece (extended)', bio: 'Nitin & Riya daughter. Young entrepreneur with a bead jewellery business.', religion: 'Hindu', nativeLanguage: 'Hindi', hometown: 'Bengaluru', tags: ['youth'], side: 'spouse', parentIds: ['aff-rao-3', 'aff-meh-3'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am5m1', title: 'Born in Bengaluru', year: 2009, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-6', name: 'Harsh Mehta', birthYear: 1982, birthPlace: 'Ahmedabad, Gujarat', currentPlace: 'Dubai, UAE', occupation: 'Real Estate Developer', gender: 'male', relationship: 'brother-in-law (extended)', bio: "Riya's brother. Developed premium residential townships in Dubai.", religion: 'Hindu', nativeLanguage: 'Gujarati', hometown: 'Ahmedabad', tags: [], side: 'spouse', parentIds: ['aff-meh-1', 'aff-meh-2'], spouseIds: ['aff-meh-7'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am6m1', title: 'Born in Ahmedabad', year: 1982, type: 'birth' }, { id: 'am6m2', title: 'Moved to Dubai', year: 2010, type: 'relocation' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-7', name: 'Fatima Al-Rashid', birthYear: 1985, birthPlace: 'Dubai, UAE', currentPlace: 'Dubai, UAE', occupation: 'Interior Architect', gender: 'female', relationship: 'sister-in-law (extended)', bio: "Harsh's wife. Emirati interior architect who blends Islamic and Indian motifs.", religion: 'Muslim', nativeLanguage: 'Arabic', hometown: 'Dubai', tags: ['artist'], side: 'spouse', parentIds: [], spouseIds: ['aff-meh-6'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am7m1', title: 'Born in Dubai', year: 1985, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-8', name: 'Omar Mehta', birthYear: 2013, birthPlace: 'Dubai, UAE', currentPlace: 'Dubai, UAE', occupation: 'School Student', gender: 'male', relationship: 'nephew (extended)', bio: 'Harsh & Fatima son. Bilingual — Arabic and Hindi.', religion: 'Muslim', nativeLanguage: 'Arabic', hometown: 'Dubai', tags: ['youth'], side: 'spouse', parentIds: ['aff-meh-6', 'aff-meh-7'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am8m1', title: 'Born in Dubai', year: 2013, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-9', name: 'Yusuf Mehta', birthYear: 1949, birthPlace: 'Ahmedabad, Gujarat', currentPlace: 'Ahmedabad, Gujarat', occupation: 'Retired Chemist (ISRO)', gender: 'male', relationship: 'uncle (extended)', bio: "Sudhir's elder brother. Worked at ISRO for 35 years. Received Padma Shri.", religion: 'Hindu', nativeLanguage: 'Gujarati', hometown: 'Ahmedabad', tags: ['elder', 'scholar', 'veteran'], side: 'spouse', parentIds: [], spouseIds: ['aff-meh-10'], generation: 1, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am9m1', title: 'Born in Ahmedabad', year: 1949, type: 'birth' }, { id: 'am9m2', title: 'Joined ISRO', year: 1972, type: 'career' }, { id: 'am9m3', title: 'Received Padma Shri', year: 2010, type: 'achievement' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-meh-10', name: 'Kokila Mehta', birthYear: 1952, birthPlace: 'Vadodara, Gujarat', currentPlace: 'Ahmedabad, Gujarat', occupation: 'Retired Banker (SBI)', gender: 'female', relationship: 'aunt (extended)', bio: "Yusuf's wife. Retired as DGM from State Bank of India.", religion: 'Hindu', nativeLanguage: 'Gujarati', hometown: 'Vadodara', tags: ['elder'], side: 'spouse', parentIds: [], spouseIds: ['aff-meh-9'], generation: 1, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'mehta-family', affiliatedFamilyName: 'Mehta Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'am10m1', title: 'Born in Vadodara', year: 1952, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },

  // ── Affiliated Family: Rao Family extended (additional Rao relatives) ────────
  { id: 'aff-rao-4', name: 'Ramesh Rao', birthYear: 1946, deathYear: 2018, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'Retired Judge', gender: 'male', relationship: 'grandfather-in-law', bio: "Shyam Rao's father. Patriarch of the Rao family. Retired district judge.", religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Hyderabad', tags: ['elder', 'patriarch'], side: 'spouse', parentIds: [], spouseIds: ['aff-rao-5'], generation: 0, isAlive: false, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar4m1', title: 'Born in Hyderabad', year: 1946, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-5', name: 'Saraswati Rao', birthYear: 1950, birthPlace: 'Warangal, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'Retired Headmistress', gender: 'female', relationship: 'grandmother-in-law', bio: "Shyam Rao's mother. First woman headmistress in her district.", religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Warangal', tags: ['elder', 'matriarch', 'scholar'], side: 'spouse', parentIds: [], spouseIds: ['aff-rao-4'], generation: 0, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar5m1', title: 'Born in Warangal', year: 1950, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-6', name: 'Sudha Rao', birthYear: 1980, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'Fashion Designer', gender: 'female', relationship: 'sister-in-law', bio: "Shyam Rao's daughter. Runs a bridal couture studio in Banjara Hills.", religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Hyderabad', tags: ['artist'], side: 'spouse', parentIds: ['aff-rao-1', 'aff-rao-2'], spouseIds: ['aff-rao-7'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar6m1', title: 'Born in Hyderabad', year: 1980, type: 'birth' }, { id: 'ar6m2', title: 'Opened Sudha Couture', year: 2015, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-7', name: 'Kiran Reddy', birthYear: 1977, birthPlace: 'Vijayawada, Andhra Pradesh', currentPlace: 'Hyderabad, Telangana', occupation: 'Film Director', gender: 'male', relationship: 'brother-in-law', bio: "Sudha's husband. Directed two Telugu blockbusters.", religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Vijayawada', tags: ['artist'], side: 'spouse', parentIds: [], spouseIds: ['aff-rao-6'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar7m1', title: 'Born in Vijayawada', year: 1977, type: 'birth' }, { id: 'ar7m2', title: 'Directed debut blockbuster', year: 2016, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-8', name: 'Tanisha Reddy', birthYear: 2006, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'School Student', gender: 'female', relationship: 'niece-in-law', bio: 'Sudha & Kiran daughter. Aspiring actress — already done two ad films.', religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Hyderabad', tags: ['youth', 'artist'], side: 'spouse', parentIds: ['aff-rao-6', 'aff-rao-7'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar8m1', title: 'Born in Hyderabad', year: 2006, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-9', name: 'Arjun Rao', birthYear: 1978, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'Neurosurgeon', gender: 'male', relationship: 'brother-in-law', bio: "Shyam Rao's youngest son. Head of Neurosurgery at Apollo Hospital Hyderabad.", religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Hyderabad', tags: ['scholar'], side: 'spouse', parentIds: ['aff-rao-1', 'aff-rao-2'], spouseIds: ['aff-rao-10'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar9m1', title: 'Born in Hyderabad', year: 1978, type: 'birth' }, { id: 'ar9m2', title: 'Joined Apollo as Head of Neurosurgery', year: 2015, type: 'career' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-10', name: 'Shalini Rao', birthYear: 1981, birthPlace: 'Bengaluru, Karnataka', currentPlace: 'Hyderabad, Telangana', occupation: 'Anaesthesiologist', gender: 'female', relationship: 'sister-in-law', bio: "Arjun's wife. Anaesthesiologist at Apollo, known for her calm demeanor in the OT.", religion: 'Hindu', nativeLanguage: 'Kannada', hometown: 'Bengaluru', tags: ['scholar'], side: 'spouse', parentIds: [], spouseIds: ['aff-rao-9'], generation: 2, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar10m1', title: 'Born in Bengaluru', year: 1981, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-11', name: 'Dev Rao', birthYear: 2008, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'School Student', gender: 'male', relationship: 'nephew-in-law', bio: 'Arjun & Shalini son. National-level chess player.', religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Hyderabad', tags: ['youth'], side: 'spouse', parentIds: ['aff-rao-9', 'aff-rao-10'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar11m1', title: 'Born in Hyderabad', year: 2008, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-12', name: 'Ishaan Rao', birthYear: 2011, birthPlace: 'Hyderabad, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'School Student', gender: 'male', relationship: 'nephew-in-law', bio: 'Arjun & Shalini younger son. Loves robotics.', religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Hyderabad', tags: ['youth'], side: 'spouse', parentIds: ['aff-rao-9', 'aff-rao-10'], spouseIds: [], generation: 3, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar12m1', title: 'Born in Hyderabad', year: 2011, type: 'birth' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-rao-13', name: 'Usha Rao Sr.', birthYear: 1925, deathYear: 2010, birthPlace: 'Nalgonda, Telangana', currentPlace: 'Hyderabad, Telangana', occupation: 'Homemaker', gender: 'female', relationship: 'great-grandmother-in-law', bio: "Ramesh Rao's mother. The original matriarch who moved the family from a village to Hyderabad.", religion: 'Hindu', nativeLanguage: 'Telugu', hometown: 'Nalgonda', tags: ['elder'], side: 'spouse', parentIds: [], spouseIds: [], generation: 0, isAlive: false, networkGroup: 'affiliated', affiliatedFamilyId: 'rao-family', affiliatedFamilyName: 'Rao Family', affiliatedJunctionId: 'g2-2', milestones: [{ id: 'ar13m1', title: 'Born in Nalgonda', year: 1925, type: 'birth' }, { id: 'ar13m2', title: 'Moved family to Hyderabad', year: 1955, type: 'relocation' }], addedBy: 'Priya Sharma', addedAt: '2024-07-01' },
  { id: 'aff-iye-14', name: 'Padmavathi Iyer', birthYear: 1930, deathYear: 2015, birthPlace: 'Thanjavur, Tamil Nadu', currentPlace: 'Chennai, Tamil Nadu', occupation: 'Homemaker', gender: 'female', relationship: 'grandmother-in-law', bio: "Venkataraman Iyer's mother. The family's link to Thanjavur Brahmin cultural traditions.", religion: 'Hindu', nativeLanguage: 'Tamil', hometown: 'Thanjavur', tags: ['elder'], side: 'spouse', parentIds: [], spouseIds: [], generation: 0, isAlive: false, networkGroup: 'affiliated', affiliatedFamilyId: 'iyer-family', affiliatedFamilyName: 'Iyer Family', affiliatedJunctionId: 'g2-5', milestones: [{ id: 'ai14m1', title: 'Born in Thanjavur', year: 1930, type: 'birth' }], addedBy: 'Ashok Mishra', addedAt: '2024-07-01' },
  { id: 'aff-kap-13', name: 'Renu Kapoor', birthYear: 1955, birthPlace: 'Amritsar, Punjab', currentPlace: 'Mumbai, Maharashtra', occupation: 'Homemaker', gender: 'female', relationship: 'aunt-in-law', bio: "Mahesh Kapoor's younger sister. Settled in Mumbai after marriage. Known for langar seva.", religion: 'Hindu', nativeLanguage: 'Punjabi', hometown: 'Amritsar', tags: ['elder'], side: 'spouse', parentIds: [], spouseIds: [], generation: 1, isAlive: true, networkGroup: 'affiliated', affiliatedFamilyId: 'kapoor-family', affiliatedFamilyName: 'Kapoor Family', affiliatedJunctionId: 'g2-3', milestones: [{ id: 'ak13m1', title: 'Born in Amritsar', year: 1955, type: 'birth' }], addedBy: 'Deepak Sharma', addedAt: '2024-07-01' },
]

export const familyFeed: FamilyEvent[] = [
  {
    id: 'f1',
    type: 'member_added',
    actorName: 'Rahul Sharma',
    subjectName: 'Ramchandra Sharma',
    message: 'added Great Grandfather Ramchandra Sharma to the family tree',
    timestamp: '2024-05-10T09:00:00Z',
    emoji: '👴',
  },
  {
    id: 'f2',
    type: 'story_added',
    actorName: 'Suresh Kumar Sharma',
    subjectName: 'Ramchandra Sharma',
    message: 'added a story "The Morning Ritual" for Dada Ramchandra',
    timestamp: '2024-05-10T10:30:00Z',
    emoji: '📖',
  },
  {
    id: 'f3',
    type: 'invite_joined',
    actorName: 'Deepak Sharma',
    subjectName: 'Arjun Sharma',
    message: 'joined via WhatsApp invite and added Arjun and Riya to the tree',
    timestamp: '2024-05-09T15:00:00Z',
    emoji: '🎉',
  },
  {
    id: 'f4',
    type: 'memory_added',
    actorName: 'Priya Sharma',
    subjectName: 'Diwali 2023',
    message: 'uploaded 12 photos from Diwali 2023 family reunion in Nagpur',
    timestamp: '2024-05-08T18:00:00Z',
    emoji: '🪔',
  },
  {
    id: 'f5',
    type: 'voice_added',
    actorName: 'Rahul Sharma',
    subjectName: 'Suresh Kumar Sharma',
    message: "recorded Dada's voice story about founding Saraswati Vidyalaya",
    timestamp: '2024-05-07T11:00:00Z',
    emoji: '🎙️',
  },
  {
    id: 'f6',
    type: 'member_added',
    actorName: 'Ashok Mishra',
    subjectName: 'Ananya Mishra',
    message: 'added Ananya Mishra to the family tree',
    timestamp: '2024-05-06T09:00:00Z',
    emoji: '✨',
  },
  {
    id: 'f7',
    type: 'milestone_added',
    actorName: 'Kavitha Mishra',
    subjectName: 'Ananya Mishra',
    message: "added milestone: Ananya published her first story in Kids' Monthly 2023",
    timestamp: '2024-05-05T14:00:00Z',
    emoji: '🏆',
  },
]

export const sampleMemories: MemoryItem[] = [
  {
    id: 'mem1',
    title: 'Diwali Reunion 2023 — Nagpur',
    description: "Full family gathered at Dada-Dadi's home in Nagpur. 4 generations under one roof for the first time.",
    photoUrl: 'https://images.unsplash.com/photo-1604423948807-8ace6e71c3e5?w=400',
    eventType: 'festival',
    year: 2023,
    date: '2023-11-12',
    taggedMemberIds: ['g1-1', 'g1-2', 'g2-1', 'g2-2', 'g3-1', 'g3-2'],
    uploadedBy: 'Priya Sharma',
    uploadedAt: '2024-01-15',
  },
  {
    id: 'mem2',
    title: "Vikram & Priya's Wedding 1998",
    description: 'The big wedding that merged the Sharma and Mishra families. Held across 3 days in Nagpur.',
    photoUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400',
    eventType: 'wedding',
    year: 1998,
    date: '1998-02-15',
    taggedMemberIds: ['g2-1', 'g2-2', 'g1-1', 'g1-2', 'g1-3', 'g1-4'],
    uploadedBy: 'Suresh Kumar Sharma',
    uploadedAt: '2024-01-10',
  },
  {
    id: 'mem3',
    title: "Rahul's Graduation Ceremony 2022",
    description: 'B.E. Computer Science convocation at Pune University. Whole family drove 4 hours to attend.',
    photoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400',
    eventType: 'graduation',
    year: 2022,
    date: '2022-06-20',
    taggedMemberIds: ['g3-1', 'g2-1', 'g2-2', 'g1-1', 'g1-2'],
    uploadedBy: 'Vikram Sharma',
    uploadedAt: '2024-01-12',
  },
  {
    id: 'mem4',
    title: "Riya's Bharatanatyam Arangetram 2021",
    description: 'First stage performance. Sunita cried through the entire show. The whole family flew to Mumbai.',
    photoUrl: 'https://images.unsplash.com/photo-1541462608143-67571c6738dd?w=400',
    eventType: 'other',
    year: 2021,
    date: '2021-08-15',
    taggedMemberIds: ['g3-4', 'g2-3', 'g2-4'],
    uploadedBy: 'Deepak Sharma',
    uploadedAt: '2024-01-18',
  },
  {
    id: 'mem5',
    title: "Suresh Dada's 75th Birthday — 2020",
    description: 'Virtual celebration during COVID. 40 family members joined from 8 cities. Dada sang a song on camera.',
    photoUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400',
    eventType: 'family-gathering',
    year: 2020,
    date: '2020-01-10',
    taggedMemberIds: ['g1-1', 'g1-2', 'g2-1', 'g2-2', 'g2-3', 'g2-4'],
    uploadedBy: 'Rahul Sharma',
    uploadedAt: '2024-01-20',
  },
  {
    id: 'mem6',
    title: 'Char Dham Yatra 2019',
    description: "Suresh Dada and Laxmi Dadi's lifelong dream fulfilled — all four sacred dhams visited in 30 days.",
    photoUrl: 'https://images.unsplash.com/photo-1544985361-b420d7a77043?w=400',
    eventType: 'travel',
    year: 2019,
    date: '2019-05-01',
    taggedMemberIds: ['g1-1', 'g1-2'],
    uploadedBy: 'Suresh Kumar Sharma',
    uploadedAt: '2024-02-01',
  },
]

export const sampleVoiceNotes: VoiceNote[] = [
  {
    id: 'v1',
    title: "Dada's story about founding Saraswati Vidyalaya",
    durationSeconds: 187,
    transcription: 'In 1975, I had only 500 rupees in my pocket and a dream. I rented a small room in Nagpur, bought a blackboard, and put a notice in the colony — "Free classes for children who cannot afford school." The first day, 7 students came. By the end of year one, we had 80 children...',
    language: 'Hindi',
    recordedBy: 'Rahul Sharma',
    recordedAt: '2024-05-07T11:00:00Z',
    memberId: 'g1-1',
  },
  {
    id: 'v2',
    title: "Nani's memory of Partition days",
    durationSeconds: 234,
    transcription: 'We were in Kanpur when the news came. Your Nana locked the doors and said — "We are not going anywhere, this is our Hindustan." Neighbors from different religions protected each other. That is the India I know...',
    language: 'Hindi',
    recordedBy: 'Priya Sharma',
    recordedAt: '2024-04-15T16:00:00Z',
    memberId: 'g1-4',
  },
  {
    id: 'v3',
    title: "Dadi's dal baati churma recipe",
    durationSeconds: 412,
    transcription: 'First you take the wheat flour — not the fine atta, the coarse one from chakki. Add salt, ajwain, and ghee — pure desi ghee, not that white butter. Make a stiff dough and shape into balls the size of your fist...',
    language: 'Hindi',
    recordedBy: 'Sneha Sharma',
    recordedAt: '2024-03-10T14:30:00Z',
    memberId: 'g1-2',
  },
]
