import { FamilyMember, FamilyEvent, MemoryItem, VoiceNote } from './types'

export const sampleFamilyMembers: FamilyMember[] = [
  // Generation 0 — Great Grandparents (Paternal)
  {
    id: 'g0-1',
    name: 'Ramchandra Sharma',
    birthYear: 1920,
    deathYear: 1995,
    birthPlace: 'Varanasi, Uttar Pradesh',
    currentPlace: 'Varanasi, Uttar Pradesh',
    occupation: 'Sanskrit Scholar & Priest',
    gender: 'male',
    relationship: 'great-grandfather',
    bio: 'A revered Vedic scholar who taught Sanskrit at Kashi Vidyapith. Known for his morning prayers by the Ganga ghats and encyclopedic memory of shlokas.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Varanasi',
    tags: ['elder', 'patriarch', 'scholar', 'historian'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['g0-2'],
    generation: 0,
    isAlive: false,
    milestones: [
      { id: 'm1', title: 'Born in Varanasi', year: 1920, type: 'birth' },
      { id: 'm2', title: 'Joined Kashi Vidyapith', year: 1942, type: 'career' },
      { id: 'm3', title: 'Married Savitri Devi', year: 1940, type: 'marriage' },
      { id: 'm4', title: 'Published Gita Commentary', year: 1965, type: 'achievement' },
    ],
    stories: [
      {
        id: 's1',
        title: 'The Morning Ritual',
        content: 'Every morning at 4am, Ramchandra Sharma would walk barefoot to the Manikarnika Ghat, dip in the Ganga, and recite 108 shlokas before sunrise. This practice never broke for 60 years — not even on the day of Partition riots in 1947, when he lit a lamp on the ghat and prayed for peace.',
        author: 'Suresh Sharma',
        createdAt: '2024-01-15',
        aiGenerated: false,
      }
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g0-2',
    name: 'Savitri Sharma',
    birthYear: 1923,
    deathYear: 2001,
    birthPlace: 'Allahabad, Uttar Pradesh',
    occupation: 'Homemaker & Ayurvedic Healer',
    gender: 'female',
    relationship: 'great-grandmother',
    bio: 'Savitri was famous across three mohallas for her herbal remedies and wisdom. She fed anyone who came to her door, even during scarcity.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Allahabad',
    tags: ['elder', 'matriarch', 'historian'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['g0-1'],
    generation: 0,
    isAlive: false,
    milestones: [
      { id: 'm5', title: 'Born in Allahabad', year: 1923, type: 'birth' },
      { id: 'm6', title: 'Married Ramchandra', year: 1940, type: 'marriage' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g0-3',
    name: 'Jagdish Prasad Mishra',
    birthYear: 1918,
    deathYear: 1990,
    birthPlace: 'Lucknow, Uttar Pradesh',
    occupation: 'Government Officer',
    gender: 'male',
    relationship: 'great-grandfather',
    bio: 'Served in the ICS during British India. Participated in the freedom movement secretly.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Lucknow',
    tags: ['elder', 'patriarch', 'veteran'],
    side: 'maternal',
    parentIds: [],
    spouseIds: ['g0-4'],
    generation: 0,
    isAlive: false,
    milestones: [
      { id: 'm7', title: 'Born in Lucknow', year: 1918, type: 'birth' },
      { id: 'm8', title: 'Joined Civil Service', year: 1940, type: 'career' },
      { id: 'm9', title: 'India Independence witnessed', year: 1947, type: 'achievement' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-10',
  },
  {
    id: 'g0-4',
    name: 'Kamla Devi Mishra',
    birthYear: 1922,
    deathYear: 1998,
    birthPlace: 'Kanpur, Uttar Pradesh',
    occupation: 'Homemaker',
    gender: 'female',
    relationship: 'great-grandmother',
    bio: 'Known for her devotion and her Tulsidas recitation every evening. Her bhajans would fill the entire street.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Kanpur',
    tags: ['elder', 'matriarch'],
    side: 'maternal',
    parentIds: [],
    spouseIds: ['g0-3'],
    generation: 0,
    isAlive: false,
    milestones: [
      { id: 'm10', title: 'Born in Kanpur', year: 1922, type: 'birth' },
      { id: 'm11', title: 'Married Jagdish Prasad', year: 1940, type: 'marriage' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-10',
  },
  // Generation 1 — Grandparents (Paternal)
  {
    id: 'g1-1',
    name: 'Suresh Kumar Sharma',
    birthYear: 1945,
    birthPlace: 'Varanasi, Uttar Pradesh',
    currentPlace: 'Nagpur, Maharashtra',
    occupation: 'Retired School Principal',
    gender: 'male',
    relationship: 'grandfather',
    bio: 'First in the family to move out of UP. Established a school in Nagpur which now has 2000 students. Loved cricket and recited poetry in Urdu.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['elder', 'patriarch', 'scholar'],
    side: 'paternal',
    parentIds: ['g0-1', 'g0-2'],
    spouseIds: ['g1-2'],
    generation: 1,
    isAlive: true,
    milestones: [
      { id: 'm12', title: 'Born in Varanasi', year: 1945, type: 'birth' },
      { id: 'm13', title: 'B.Ed from BHU', year: 1968, type: 'education' },
      { id: 'm14', title: 'Moved to Nagpur', year: 1970, type: 'relocation' },
      { id: 'm15', title: 'Founded Saraswati Vidyalaya', year: 1975, type: 'achievement' },
      { id: 'm16', title: 'Married Laxmi Devi', year: 1968, type: 'marriage' },
    ],
    stories: [
      {
        id: 's2',
        title: 'The Move to Nagpur',
        content: 'In 1970, Suresh boarded a train to Nagpur with only his degrees, a dhoti, and his father\'s blessings. He had secured a teaching job by writing 40 application letters by hand. "Education is the only wealth that cannot be stolen," he always said.',
        author: 'Vikram Sharma',
        createdAt: '2024-02-20',
      }
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g1-2',
    name: 'Laxmi Devi Sharma',
    birthYear: 1948,
    birthPlace: 'Nagpur, Maharashtra',
    currentPlace: 'Nagpur, Maharashtra',
    occupation: 'Retired Teacher',
    gender: 'female',
    relationship: 'grandmother',
    bio: 'Taught Hindi to thousands of students. Famous for her Narali Poornima celebrations blending UP and Maharashtra traditions. Her dal baati churma is legendary.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['elder', 'matriarch'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['g1-1'],
    generation: 1,
    isAlive: true,
    milestones: [
      { id: 'm17', title: 'Born in Nagpur', year: 1948, type: 'birth' },
      { id: 'm18', title: 'Completed BA Hindi', year: 1969, type: 'education' },
      { id: 'm19', title: 'Married Suresh Kumar', year: 1968, type: 'marriage' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  // Generation 1 — Grandparents (Maternal)
  {
    id: 'g1-3',
    name: 'Ramdas Mishra',
    birthYear: 1943,
    birthPlace: 'Lucknow, Uttar Pradesh',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Retired Bank Manager',
    gender: 'male',
    relationship: 'grandfather',
    bio: 'Rose from clerk to Branch Manager in 30 years at SBI. Known for giving loans to poor farmers when no one else would.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: ['elder', 'patriarch'],
    side: 'maternal',
    parentIds: ['g0-3', 'g0-4'],
    spouseIds: ['g1-4'],
    generation: 1,
    isAlive: true,
    milestones: [
      { id: 'm20', title: 'Born in Lucknow', year: 1943, type: 'birth' },
      { id: 'm21', title: 'Joined SBI', year: 1965, type: 'career' },
      { id: 'm22', title: 'Promoted to Branch Manager', year: 1985, type: 'achievement' },
      { id: 'm23', title: 'Married Pushpa Devi', year: 1967, type: 'marriage' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-01-05',
  },
  {
    id: 'g1-4',
    name: 'Pushpa Devi Mishra',
    birthYear: 1947,
    birthPlace: 'Kanpur, Uttar Pradesh',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Homemaker & Social Worker',
    gender: 'female',
    relationship: 'grandmother',
    bio: 'Founded a women\'s self-help group in Pune that empowered 300+ women. Loves Bollywood songs from the 60s and can recite Gulzar verses by heart.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Kanpur',
    tags: ['elder', 'matriarch', 'veteran'],
    side: 'maternal',
    parentIds: [],
    spouseIds: ['g1-3'],
    generation: 1,
    isAlive: true,
    milestones: [
      { id: 'm24', title: 'Born in Kanpur', year: 1947, type: 'birth' },
      { id: 'm25', title: 'Married Ramdas Mishra', year: 1967, type: 'marriage' },
      { id: 'm26', title: 'Founded SHG in Pune', year: 1990, type: 'achievement' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-01-05',
  },
  // Generation 2 — Parents
  {
    id: 'g2-1',
    name: 'Vikram Sharma',
    birthYear: 1972,
    birthPlace: 'Nagpur, Maharashtra',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Civil Engineer',
    gender: 'male',
    relationship: 'father',
    bio: 'Senior civil engineer who built bridges and highways across Maharashtra. Took early morning cycle rides every day for 30 years. Loves Marathi theater.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['patriarch'],
    side: 'paternal',
    parentIds: ['g1-1', 'g1-2'],
    spouseIds: ['g2-2'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm27', title: 'Born in Nagpur', year: 1972, type: 'birth' },
      { id: 'm28', title: 'B.E. Civil from VNIT Nagpur', year: 1994, type: 'education' },
      { id: 'm29', title: 'Married Priya Mishra', year: 1998, type: 'marriage' },
      { id: 'm30', title: 'Built Pune-Nashik Expressway Section', year: 2008, type: 'achievement' },
      { id: 'm31', title: 'Moved to Pune', year: 1998, type: 'relocation' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g2-2',
    name: 'Priya Sharma',
    birthYear: 1975,
    birthPlace: 'Pune, Maharashtra',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'School Principal',
    gender: 'female',
    relationship: 'mother',
    bio: 'Principal of a reputed school in Pune. Advocate for girl child education. Runs a free tuition center on weekends. Loves gardening.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: ['matriarch', 'scholar'],
    side: 'maternal',
    parentIds: ['g1-3', 'g1-4'],
    spouseIds: ['g2-1'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm32', title: 'Born in Pune', year: 1975, type: 'birth' },
      { id: 'm33', title: 'M.Ed from Pune University', year: 1997, type: 'education' },
      { id: 'm34', title: 'Married Vikram Sharma', year: 1998, type: 'marriage' },
      { id: 'm35', title: 'Became School Principal', year: 2015, type: 'career' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  // Generation 2 — Uncle/Aunt (Paternal)
  {
    id: 'g2-3',
    name: 'Deepak Sharma',
    birthYear: 1976,
    birthPlace: 'Nagpur, Maharashtra',
    currentPlace: 'Mumbai, Maharashtra',
    occupation: 'Chartered Accountant',
    gender: 'male',
    relationship: 'uncle',
    bio: "Vikram's younger brother. Moved to Mumbai for work. Known as the 'finance brain' of the family. Loves Sachin Tendulkar and cricket statistics.",
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Nagpur',
    tags: ['scholar'],
    side: 'paternal',
    parentIds: ['g1-1', 'g1-2'],
    spouseIds: ['g2-4'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm36', title: 'Born in Nagpur', year: 1976, type: 'birth' },
      { id: 'm37', title: 'Cleared CA Exams', year: 1999, type: 'education' },
      { id: 'm38', title: 'Married Sunita', year: 2002, type: 'marriage' },
      { id: 'm39', title: 'Moved to Mumbai', year: 2000, type: 'relocation' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-15',
  },
  {
    id: 'g2-4',
    name: 'Sunita Sharma',
    birthYear: 1978,
    birthPlace: 'Mumbai, Maharashtra',
    currentPlace: 'Mumbai, Maharashtra',
    occupation: 'Fashion Designer',
    gender: 'female',
    relationship: 'aunt',
    bio: "Creates traditional Indian wear with modern designs. Runs her own label 'Rang Barse'. Blends Banarasi silk with contemporary cuts.",
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Marathi',
    hometown: 'Mumbai',
    tags: ['artist'],
    side: 'paternal',
    parentIds: [],
    spouseIds: ['g2-3'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm40', title: 'Born in Mumbai', year: 1978, type: 'birth' },
      { id: 'm41', title: 'NIFT Graduate', year: 2000, type: 'education' },
      { id: 'm42', title: 'Launched Rang Barse', year: 2010, type: 'achievement' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-15',
  },
  // Generation 2 — Uncle (Maternal)
  {
    id: 'g2-5',
    name: 'Ashok Mishra',
    birthYear: 1978,
    birthPlace: 'Pune, Maharashtra',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'Software Architect',
    gender: 'male',
    relationship: 'uncle',
    bio: "Priya's brother. Works at a top tech company in Bengaluru. Early adopter of everything tech.",
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: [],
    side: 'maternal',
    parentIds: ['g1-3', 'g1-4'],
    spouseIds: ['g2-6'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm43', title: 'Born in Pune', year: 1978, type: 'birth' },
      { id: 'm44', title: 'B.Tech from IIT Bombay', year: 2000, type: 'education' },
      { id: 'm45', title: 'Married Kavitha', year: 2005, type: 'marriage' },
      { id: 'm46', title: 'Moved to Bengaluru', year: 2002, type: 'relocation' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-01-10',
  },
  {
    id: 'g2-6',
    name: 'Kavitha Mishra',
    birthYear: 1980,
    birthPlace: 'Chennai, Tamil Nadu',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'Data Scientist',
    gender: 'female',
    relationship: 'aunt',
    bio: 'South meets North! Kavitha brought idli-sambar to Mishra family pujas. Works on AI models at a global tech firm.',
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Tamil',
    hometown: 'Chennai',
    tags: ['scholar'],
    side: 'maternal',
    parentIds: [],
    spouseIds: ['g2-5'],
    generation: 2,
    isAlive: true,
    milestones: [
      { id: 'm47', title: 'Born in Chennai', year: 1980, type: 'birth' },
      { id: 'm48', title: 'M.Sc. Statistics from IISc', year: 2003, type: 'education' },
      { id: 'm49', title: 'Married Ashok Mishra', year: 2005, type: 'marriage' },
    ],
    addedBy: 'Priya Sharma',
    addedAt: '2024-01-10',
  },
  // Generation 3 — You & Siblings
  {
    id: 'g3-1',
    name: 'Rahul Sharma',
    birthYear: 2000,
    birthPlace: 'Pune, Maharashtra',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Software Developer & Family Historian',
    gender: 'male',
    relationship: 'self',
    bio: 'Built this Family Graph to preserve our roots. CS graduate from Pune University. Loves trekking in Sahyadri, playing tabla, and spicy misal pav.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: ['youth', 'scholar', 'historian'],
    side: 'both',
    parentIds: ['g2-1', 'g2-2'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    role: 'admin',
    milestones: [
      { id: 'm50', title: 'Born in Pune', year: 2000, type: 'birth' },
      { id: 'm51', title: 'B.E. Computer Science', year: 2022, type: 'education' },
      { id: 'm52', title: 'Built Family Graph App', year: 2024, type: 'achievement' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  {
    id: 'g3-2',
    name: 'Sneha Sharma',
    birthYear: 2003,
    birthPlace: 'Pune, Maharashtra',
    currentPlace: 'Pune, Maharashtra',
    occupation: 'Medical Student',
    gender: 'female',
    relationship: 'sister',
    bio: 'MBBS 3rd year at BJ Medical College. Wants to be a pediatrician. Paints in her free time.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Pune',
    tags: ['youth', 'scholar'],
    side: 'both',
    parentIds: ['g2-1', 'g2-2'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm53', title: 'Born in Pune', year: 2003, type: 'birth' },
      { id: 'm54', title: 'NEET qualified', year: 2021, type: 'achievement' },
      { id: 'm55', title: 'Started MBBS at BJ Medical', year: 2021, type: 'education' },
    ],
    addedBy: 'Rahul Sharma',
    addedAt: '2024-01-01',
  },
  // Generation 3 — Cousins (Paternal)
  {
    id: 'g3-3',
    name: 'Arjun Sharma',
    birthYear: 2004,
    birthPlace: 'Mumbai, Maharashtra',
    currentPlace: 'Mumbai, Maharashtra',
    occupation: 'IIT Student',
    gender: 'male',
    relationship: 'cousin',
    bio: "Deepak's son. JEE Advanced qualified. Loves competitive programming and chess. Wants to build rockets.",
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Mumbai',
    tags: ['youth', 'scholar'],
    side: 'paternal',
    parentIds: ['g2-3', 'g2-4'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm56', title: 'Born in Mumbai', year: 2004, type: 'birth' },
      { id: 'm57', title: 'Won State Chess Championship', year: 2020, type: 'achievement' },
      { id: 'm58', title: 'Qualified JEE Advanced', year: 2022, type: 'achievement' },
    ],
    addedBy: 'Deepak Sharma',
    addedAt: '2024-02-01',
  },
  {
    id: 'g3-4',
    name: 'Riya Sharma',
    birthYear: 2007,
    birthPlace: 'Mumbai, Maharashtra',
    currentPlace: 'Mumbai, Maharashtra',
    occupation: 'School Student',
    gender: 'female',
    relationship: 'cousin',
    bio: 'National-level Bharatanatyam dancer. Dreams of combining classical dance with contemporary music.',
    gotra: 'Bharadwaj',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Mumbai',
    tags: ['youth', 'artist', 'child'],
    side: 'paternal',
    parentIds: ['g2-3', 'g2-4'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm59', title: 'Born in Mumbai', year: 2007, type: 'birth' },
      { id: 'm60', title: 'Performed at National Dance Festival', year: 2023, type: 'achievement' },
    ],
    addedBy: 'Sunita Sharma',
    addedAt: '2024-02-01',
  },
  // Generation 3 — Cousins (Maternal)
  {
    id: 'g3-5',
    name: 'Karan Mishra',
    birthYear: 2006,
    birthPlace: 'Bengaluru, Karnataka',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'School Student',
    gender: 'male',
    relationship: 'cousin',
    bio: "Ashok's son. Born in Bengaluru, speaks 4 languages. Won robotics competitions across south India.",
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Hindi',
    hometown: 'Bengaluru',
    tags: ['youth', 'scholar', 'child'],
    side: 'maternal',
    parentIds: ['g2-5', 'g2-6'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm61', title: 'Born in Bengaluru', year: 2006, type: 'birth' },
      { id: 'm62', title: 'Won South India Robotics Championship', year: 2023, type: 'achievement' },
    ],
    addedBy: 'Ashok Mishra',
    addedAt: '2024-01-20',
  },
  {
    id: 'g3-6',
    name: 'Ananya Mishra',
    birthYear: 2009,
    birthPlace: 'Bengaluru, Karnataka',
    currentPlace: 'Bengaluru, Karnataka',
    occupation: 'School Student',
    gender: 'female',
    relationship: 'cousin',
    bio: "Ashok and Kavitha's youngest. A budding author who has already published 2 short stories.",
    gotra: 'Kashyap',
    religion: 'Hindu',
    nativeLanguage: 'Tamil',
    hometown: 'Bengaluru',
    tags: ['youth', 'artist', 'child'],
    side: 'maternal',
    parentIds: ['g2-5', 'g2-6'],
    spouseIds: [],
    generation: 3,
    isAlive: true,
    milestones: [
      { id: 'm63', title: 'Born in Bengaluru', year: 2009, type: 'birth' },
      { id: 'm64', title: "Published first story in Kids' Monthly", year: 2023, type: 'achievement' },
    ],
    addedBy: 'Kavitha Mishra',
    addedAt: '2024-01-20',
  },
]

export const familyFeed: FamilyEvent[] = [
  {
    id: 'f1',
    type: 'member_added',
    actorName: 'Rahul Sharma',
    subjectName: 'Ramchandra Sharma',
    message: 'added Great Grandfather Ramchandra Sharma to the family tree',
    timestamp: '2024-05-10T09:00:00Z',
    emoji: '👴',
  },
  {
    id: 'f2',
    type: 'story_added',
    actorName: 'Suresh Kumar Sharma',
    subjectName: 'Ramchandra Sharma',
    message: 'added a story "The Morning Ritual" for Dada Ramchandra',
    timestamp: '2024-05-10T10:30:00Z',
    emoji: '📖',
  },
  {
    id: 'f3',
    type: 'invite_joined',
    actorName: 'Deepak Sharma',
    subjectName: 'Arjun Sharma',
    message: 'joined via WhatsApp invite and added Arjun and Riya to the tree',
    timestamp: '2024-05-09T15:00:00Z',
    emoji: '🎉',
  },
  {
    id: 'f4',
    type: 'memory_added',
    actorName: 'Priya Sharma',
    subjectName: 'Diwali 2023',
    message: 'uploaded 12 photos from Diwali 2023 family reunion in Nagpur',
    timestamp: '2024-05-08T18:00:00Z',
    emoji: '🪔',
  },
  {
    id: 'f5',
    type: 'voice_added',
    actorName: 'Rahul Sharma',
    subjectName: 'Suresh Kumar Sharma',
    message: "recorded Dada's voice story about founding Saraswati Vidyalaya",
    timestamp: '2024-05-07T11:00:00Z',
    emoji: '🎙️',
  },
  {
    id: 'f6',
    type: 'member_added',
    actorName: 'Ashok Mishra',
    subjectName: 'Ananya Mishra',
    message: 'added Ananya Mishra to the family tree',
    timestamp: '2024-05-06T09:00:00Z',
    emoji: '✨',
  },
  {
    id: 'f7',
    type: 'milestone_added',
    actorName: 'Kavitha Mishra',
    subjectName: 'Ananya Mishra',
    message: "added milestone: Ananya published her first story in Kids' Monthly 2023",
    timestamp: '2024-05-05T14:00:00Z',
    emoji: '🏆',
  },
]

export const sampleMemories: MemoryItem[] = [
  {
    id: 'mem1',
    title: 'Diwali Reunion 2023 — Nagpur',
    description: "Full family gathered at Dada-Dadi's home in Nagpur. 4 generations under one roof for the first time.",
    photoUrl: 'https://images.unsplash.com/photo-1604423948807-8ace6e71c3e5?w=400',
    eventType: 'festival',
    year: 2023,
    date: '2023-11-12',
    taggedMemberIds: ['g1-1', 'g1-2', 'g2-1', 'g2-2', 'g3-1', 'g3-2'],
    uploadedBy: 'Priya Sharma',
    uploadedAt: '2024-01-15',
  },
  {
    id: 'mem2',
    title: "Vikram & Priya's Wedding 1998",
    description: 'The big wedding that merged the Sharma and Mishra families. Held across 3 days in Nagpur.',
    photoUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400',
    eventType: 'wedding',
    year: 1998,
    date: '1998-02-15',
    taggedMemberIds: ['g2-1', 'g2-2', 'g1-1', 'g1-2', 'g1-3', 'g1-4'],
    uploadedBy: 'Suresh Kumar Sharma',
    uploadedAt: '2024-01-10',
  },
  {
    id: 'mem3',
    title: "Rahul's Graduation Ceremony 2022",
    description: 'B.E. Computer Science convocation at Pune University. Whole family drove 4 hours to attend.',
    photoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400',
    eventType: 'graduation',
    year: 2022,
    date: '2022-06-20',
    taggedMemberIds: ['g3-1', 'g2-1', 'g2-2', 'g1-1', 'g1-2'],
    uploadedBy: 'Vikram Sharma',
    uploadedAt: '2024-01-12',
  },
  {
    id: 'mem4',
    title: "Riya's Bharatanatyam Arangetram 2021",
    description: 'First stage performance. Sunita cried through the entire show. The whole family flew to Mumbai.',
    photoUrl: 'https://images.unsplash.com/photo-1541462608143-67571c6738dd?w=400',
    eventType: 'other',
    year: 2021,
    date: '2021-08-15',
    taggedMemberIds: ['g3-4', 'g2-3', 'g2-4'],
    uploadedBy: 'Deepak Sharma',
    uploadedAt: '2024-01-18',
  },
  {
    id: 'mem5',
    title: "Suresh Dada's 75th Birthday — 2020",
    description: 'Virtual celebration during COVID. 40 family members joined from 8 cities. Dada sang a song on camera.',
    photoUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400',
    eventType: 'family-gathering',
    year: 2020,
    date: '2020-01-10',
    taggedMemberIds: ['g1-1', 'g1-2', 'g2-1', 'g2-2', 'g2-3', 'g2-4'],
    uploadedBy: 'Rahul Sharma',
    uploadedAt: '2024-01-20',
  },
  {
    id: 'mem6',
    title: 'Char Dham Yatra 2019',
    description: "Suresh Dada and Laxmi Dadi's lifelong dream fulfilled — all four sacred dhams visited in 30 days.",
    photoUrl: 'https://images.unsplash.com/photo-1544985361-b420d7a77043?w=400',
    eventType: 'travel',
    year: 2019,
    date: '2019-05-01',
    taggedMemberIds: ['g1-1', 'g1-2'],
    uploadedBy: 'Suresh Kumar Sharma',
    uploadedAt: '2024-02-01',
  },
]

export const sampleVoiceNotes: VoiceNote[] = [
  {
    id: 'v1',
    title: "Dada's story about founding Saraswati Vidyalaya",
    durationSeconds: 187,
    transcription: 'In 1975, I had only 500 rupees in my pocket and a dream. I rented a small room in Nagpur, bought a blackboard, and put a notice in the colony — "Free classes for children who cannot afford school." The first day, 7 students came. By the end of year one, we had 80 children...',
    language: 'Hindi',
    recordedBy: 'Rahul Sharma',
    recordedAt: '2024-05-07T11:00:00Z',
    memberId: 'g1-1',
  },
  {
    id: 'v2',
    title: "Nani's memory of Partition days",
    durationSeconds: 234,
    transcription: 'We were in Kanpur when the news came. Your Nana locked the doors and said — "We are not going anywhere, this is our Hindustan." Neighbors from different religions protected each other. That is the India I know...',
    language: 'Hindi',
    recordedBy: 'Priya Sharma',
    recordedAt: '2024-04-15T16:00:00Z',
    memberId: 'g1-4',
  },
  {
    id: 'v3',
    title: "Dadi's dal baati churma recipe",
    durationSeconds: 412,
    transcription: 'First you take the wheat flour — not the fine atta, the coarse one from chakki. Add salt, ajwain, and ghee — pure desi ghee, not that white butter. Make a stiff dough and shape into balls the size of your fist...',
    language: 'Hindi',
    recordedBy: 'Sneha Sharma',
    recordedAt: '2024-03-10T14:30:00Z',
    memberId: 'g1-2',
  },
]
